package SLTB_Bimsara.Oparation;

import SLTB_Bimsara.DBCon;
import SLTB_Bimsara.Panel.BusRegistation.*;
import SLTB_sachin.Temp;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Edu
 */
public class AddNewOparation extends javax.swing.JPanel {

    private static AddNewOparation addNewOparation = null;
    protected String z;

    DefaultComboBoxModel dm = new DefaultComboBoxModel();
    DefaultComboBoxModel dr = new DefaultComboBoxModel();

    private AddNewOparation() {
        initComponents();
        String x = DBCon.getValues("OparationId", "oparations");
        int y = Integer.parseInt(x);
        String z = Integer.toString(++y);
        //System.out.println(z);
        jLabelOparationId.setText(z);
        loardcomp();

    }

    public static AddNewOparation getobj() {
        if (addNewOparation == null) {
            addNewOparation = new AddNewOparation();
        }
        return addNewOparation;
    }

    private void loardcomp() {

        //setvalueFor ComboBox----------------------------------------------
        ResultSet rs = DBCon.buscombobox("busdetailes", "BusNumber", "oparations", "BusNumber");
        try {
            while (rs.next()) {
                dm.addElement(rs.getString(1));
                jComboBoxBusNumber.setModel(dm);

            }
        } catch (SQLException ex) {
            Logger.getLogger(AddNewOparation.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBoxBusNumber.setModel(dm);

        //---------------------------------------------------------------------
        //setRoutId
        ResultSet Rl = DBCon.displayTable("RoutId", "rout");
        try {
            while (Rl.next()) {
                dr.addElement(Rl.getString(1));
                // jComboBoxBusNumber.setModel(dm);

            }
        } catch (SQLException ex) {
            Logger.getLogger(AddNewOparation.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBoxRoutId.setModel(dr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        busNo = new javax.swing.JLabel();
        busModel = new javax.swing.JLabel();
        busBrand = new javax.swing.JLabel();
        busManYear = new javax.swing.JLabel();
        busType = new javax.swing.JLabel();
        busSeats = new javax.swing.JLabel();
        busFuelCapacity = new javax.swing.JLabel();
        busSPNote = new javax.swing.JLabel();
        jComboBoxServiceType = new javax.swing.JComboBox<>();
        jTextFieldDistance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelButton = new javax.swing.JButton();
        jButtonAddButton = new javax.swing.JButton();
        jComboBoxBusNumber = new javax.swing.JComboBox<>();
        jLabelOparationId = new javax.swing.JLabel();
        jRadioButtonDutyNo1 = new javax.swing.JRadioButton();
        jRadioButtonDutyNo2 = new javax.swing.JRadioButton();
        Date date =new Date();
        SpinnerDateModel sm=
        new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        jSpinnerStartTime = new javax.swing.JSpinner(sm);
        Date date2 =new Date();
        SpinnerDateModel sm2=
        new SpinnerDateModel(date2,null,null,Calendar.HOUR_OF_DAY);
        jSpinnerEndTime = new javax.swing.JSpinner(sm2);
        jComboBoxRoutId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);

        busNo.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busNo.setText("Odjk wxlh ");

        busModel.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busModel.setText("ld¾h wxl .Kk ");

        busBrand.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busBrand.setText("nia r: wxlh  ");

        busManYear.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busManYear.setText("wdrïNl fj,dj");

        busType.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busType.setText("wjika fj,dj");

        busSeats.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busSeats.setText("ud¾. wxl ,hsia;=j ");

        busFuelCapacity.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busFuelCapacity.setText("Odjkh lrk Vqr m%ukh ");

        busSPNote.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busSPNote.setText("fiajd j¾.h");

        jComboBoxServiceType.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        jComboBoxServiceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idudkH", "k.rdka;r ", ".eñ  ießh ", "ksis ißh ", "isiq ißh " }));
        jComboBoxServiceType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServiceTypeActionPerformed(evt);
            }
        });

        jTextFieldDistance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDistanceKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("FMBindumathi", 1, 48)); // NOI18N
        jLabel1.setText("kj Odjk wxl tl;= lsßu");

        jButtonCancelButton.setBackground(new java.awt.Color(246, 73, 73));
        jButtonCancelButton.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        jButtonCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edelete.png"))); // NOI18N
        jButtonCancelButton.setText("wj,x.= lrkak ");
        jButtonCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelButtonMouseClicked(evt);
            }
        });
        jButtonCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelButtonActionPerformed(evt);
            }
        });

        jButtonAddButton.setBackground(new java.awt.Color(0, 204, 0));
        jButtonAddButton.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        jButtonAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eadd.png"))); // NOI18N
        jButtonAddButton.setText("tl;= lrkak");
        jButtonAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddButtonMouseClicked(evt);
            }
        });

        jComboBoxBusNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NC-1715" }));
        jComboBoxBusNumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxBusNumberItemStateChanged(evt);
            }
        });
        jComboBoxBusNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBusNumberActionPerformed(evt);
            }
        });

        jLabelOparationId.setText("2");

        buttonGroup1.add(jRadioButtonDutyNo1);
        jRadioButtonDutyNo1.setText("1");

        buttonGroup1.add(jRadioButtonDutyNo2);
        jRadioButtonDutyNo2.setText("2");

        JSpinner.DateEditor de=new JSpinner.DateEditor(jSpinnerStartTime,"HH:mm:ss");
        jSpinnerStartTime.setEditor(de);

        JSpinner.DateEditor de2=new JSpinner.DateEditor(jSpinnerEndTime,"HH:mm:ss");
        jSpinnerEndTime.setEditor(de2);

        jComboBoxRoutId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRoutId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRoutIdItemStateChanged(evt);
            }
        });
        jComboBoxRoutId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoutIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Km");

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*");

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");

        jButton1.setText("DEMO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(jButtonCancelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(busFuelCapacity, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(busSeats)
                                        .addComponent(busSPNote)
                                        .addComponent(busNo)
                                        .addComponent(busBrand))
                                    .addGap(27, 27, 27))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(busModel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(busManYear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(busType)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addGap(82, 82, 82)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxBusNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxServiceType, 0, 341, Short.MAX_VALUE)
                                .addComponent(jLabelOparationId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonDutyNo1)
                                    .addGap(37, 37, 37)
                                    .addComponent(jRadioButtonDutyNo2))
                                .addComponent(jSpinnerEndTime)
                                .addComponent(jSpinnerStartTime)
                                .addComponent(jComboBoxRoutId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23))))))
                .addGap(0, 294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busNo)
                    .addComponent(jLabelOparationId))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busModel)
                    .addComponent(jRadioButtonDutyNo1)
                    .addComponent(jRadioButtonDutyNo2)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busBrand)
                    .addComponent(jComboBoxBusNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busManYear)
                    .addComponent(jSpinnerStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busType)
                    .addComponent(jSpinnerEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busSeats)
                    .addComponent(jComboBoxRoutId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busFuelCapacity)
                    .addComponent(jTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busSPNote, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelButton)
                    .addComponent(jButtonAddButton)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelButtonActionPerformed

    private void jComboBoxServiceTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServiceTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServiceTypeActionPerformed

    private void jButtonCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelButtonMouseClicked
        OparationSide os = OparationSide.getobj();
        OparationTop ot = OparationTop.getobj();
        OparationMain om = OparationMain.getobj();
        AddNewOparation addNewOparation = AddNewOparation.getobj();

        ot.setVisible(true);
        om.setVisible(true);
        os.setVisible(true);
        addNewOparation.setVisible(false);
        Temp t = Temp.temp1;
        t.upsetpanel.add(ot, t.cup);
        t.mainsetpanel.add(om, t.cmain);
        t.sidesetpanel.add(os, t.cside);
    }//GEN-LAST:event_jButtonCancelButtonMouseClicked

    private void jButtonAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddButtonMouseClicked
//radioButton Declare
        try {
            jRadioButtonDutyNo1.setActionCommand("1");
            jRadioButtonDutyNo2.setActionCommand("2");

            DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
            Date d = (Date) jSpinnerStartTime.getValue();
            String time = dateFormat.format(d);
            //System.out.println(time);

            DateFormat dateFormat1 = new SimpleDateFormat("HH:mm:ss");
            Date d1 = (Date) jSpinnerEndTime.getValue();
            String time1 = dateFormat.format(d1);
            //System.out.println(time1);

            //setMainPanal
            OparationSide os = OparationSide.getobj();
            OparationTop ot = OparationTop.getobj();
            OparationMain om = OparationMain.getobj();
            AddNewOparation addNewOparation = AddNewOparation.getobj();

            ot.setVisible(true);
            om.setVisible(true);
            os.setVisible(true);
            addNewOparation.setVisible(false);
            Temp t = Temp.temp1;
            t.upsetpanel.add(ot, t.cup);
            t.mainsetpanel.add(om, t.cmain);
            t.sidesetpanel.add(os, t.cside);

            //pass value to db
            String tbName = "oparations";
            String ColumnsList = "OparationId,dutyNo,BusNumber,StartTime,EndTime,RoutIdList,Distrance,Otype";
            String c = "'" + jLabelOparationId.getText() + "','" + buttonGroup1.getSelection().getActionCommand() + "','" + jComboBoxBusNumber.getSelectedItem() + "','" + time + "','" + time1 + "','" + jComboBoxRoutId.getSelectedItem() + "','" + jTextFieldDistance.getText() + "','" + jComboBoxServiceType.getSelectedItem() + "'";
            //System.out.println(c);
            DBCon.InsertToDb(tbName, ColumnsList, c);

            //clear 
            jLabelOparationId.setText("");
            jTextFieldDistance.setText("");
            //reloads table
            om.loadTable();
            //}
        } catch (Exception e) {
            JLabel label = new JLabel(";re i,l=Kq iys; fldgia mqrjkak ");
            label.setFont(new Font("FMBindumathi", Font.BOLD, 18));
            JOptionPane jOptionPane = new JOptionPane();
            jOptionPane.setMessage(label);

            jOptionPane.setMessage(label);
            jOptionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = jOptionPane.createDialog(null, "Error");
            dialog.setVisible(true);

            OparationSide os = OparationSide.getobj();
            OparationTop ot = OparationTop.getobj();
            OparationMain om = OparationMain.getobj();
            AddNewOparation addNewOparation = AddNewOparation.getobj();
            ot.setVisible(false);
            om.setVisible(false);
            os.setVisible(false);
            addNewOparation.setVisible(true);
            Temp t = Temp.temp1;
            //t.upsetpanel.add(ot, t.cup);
            t.mainsetpanel.add(addNewOparation, t.cmain);
            //t.sidesetpanel.add(os, t.cside);
        }
    }//GEN-LAST:event_jButtonAddButtonMouseClicked

    private void jComboBoxBusNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBusNumberActionPerformed

        jComboBoxBusNumber.setModel(dm);
    }//GEN-LAST:event_jComboBoxBusNumberActionPerformed

    private void jComboBoxBusNumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxBusNumberItemStateChanged

    }//GEN-LAST:event_jComboBoxBusNumberItemStateChanged

    private void jComboBoxRoutIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRoutIdItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoutIdItemStateChanged

    private void jComboBoxRoutIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoutIdActionPerformed
//        j
    }//GEN-LAST:event_jComboBoxRoutIdActionPerformed

    private void jTextFieldDistanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDistanceKeyTyped

        char c = evt.getKeyChar();
        if (Character.isLetter(c) && !evt.isAltDown()) {
            evt.consume();
            JLabel label = new JLabel("wkal muKla w;=,alrkak ");
            label.setFont(new Font("FMBindumathi", Font.BOLD, 18));
            JOptionPane jOptionPane = new JOptionPane();
            jOptionPane.setMessage(label);

            jOptionPane.setMessage(label);
            jOptionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = jOptionPane.createDialog(null, "Error");
            dialog.setVisible(true);
        }
        String len = jTextFieldDistance.getText();
        int x = len.length();
        if (x > 5) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDistanceKeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        //jLabelOparationId.setText("");
        jTextFieldDistance.setText("123");
        jRadioButtonDutyNo1.setActionCommand("1");
        jRadioButtonDutyNo2.setActionCommand("2");
        buttonGroup1.setSelected(jRadioButtonDutyNo1.getModel(), true);

    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busBrand;
    private javax.swing.JLabel busFuelCapacity;
    private javax.swing.JLabel busManYear;
    private javax.swing.JLabel busModel;
    private javax.swing.JLabel busNo;
    private javax.swing.JLabel busSPNote;
    private javax.swing.JLabel busSeats;
    private javax.swing.JLabel busType;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddButton;
    private javax.swing.JButton jButtonCancelButton;
    private javax.swing.JComboBox<String> jComboBoxBusNumber;
    private javax.swing.JComboBox<String> jComboBoxRoutId;
    private javax.swing.JComboBox<String> jComboBoxServiceType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelOparationId;
    private javax.swing.JRadioButton jRadioButtonDutyNo1;
    private javax.swing.JRadioButton jRadioButtonDutyNo2;
    private javax.swing.JSpinner jSpinnerEndTime;
    private javax.swing.JSpinner jSpinnerStartTime;
    private javax.swing.JTextField jTextFieldDistance;
    // End of variables declaration//GEN-END:variables

}
