package SLTB_Bimsara.Route;

import SLTB_Bimsara.DBCon;
import SLTB_Bimsara.Panel.BusRegistation.*;
import SLTB_sachin.Temp;
import java.awt.Font;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Edu
 */
public class AddNewRouteId extends javax.swing.JPanel {

    private static AddNewRouteId addNewBus = null;

    private AddNewRouteId() {
        initComponents();
    }

    public static AddNewRouteId getobj() {
        if (addNewBus == null) {
            addNewBus = new AddNewRouteId();
        }
        return addNewBus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BusTypeGroup = new javax.swing.ButtonGroup();
        busNo = new javax.swing.JLabel();
        busModel = new javax.swing.JLabel();
        busBrand = new javax.swing.JLabel();
        busManYear = new javax.swing.JLabel();
        busType = new javax.swing.JLabel();
        busSPNote = new javax.swing.JLabel();
        jTextFieldRouteId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldStartPoint = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSpNotes = new javax.swing.JTextArea();
        jButtonCancelButton = new javax.swing.JButton();
        jButtonAddRouteButton = new javax.swing.JButton();
        jTextFieldToatalDistance = new javax.swing.JTextField();
        jTextFieldEndPoint = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonAA = new javax.swing.JRadioButton();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jRadioButtonD = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setForeground(new java.awt.Color(204, 0, 0));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);

        busNo.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busNo.setText("ud¾. wxlh ");

        busModel.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busModel.setText("wdrïNl ia:dkh ");

        busBrand.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busBrand.setText("wjika ia:dkh");

        busManYear.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busManYear.setText("nia r: LdKaV ");

        busType.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busType.setText("uq¨ ÿr  ");

        busSPNote.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        busSPNote.setText("úfYaI igyka ");

        jTextFieldRouteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRouteIdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("FMBindumathi", 1, 48)); // NOI18N
        jLabel1.setText("kj ud¾. wxl tl;= lsßu");

        jTextFieldStartPoint.setFont(new java.awt.Font("FMBindumathi", 0, 12)); // NOI18N
        jTextFieldStartPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStartPointActionPerformed(evt);
            }
        });

        jTextAreaSpNotes.setColumns(20);
        jTextAreaSpNotes.setFont(new java.awt.Font("FMBindumathi", 0, 12)); // NOI18N
        jTextAreaSpNotes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSpNotes);

        jButtonCancelButton.setBackground(new java.awt.Color(255, 0, 51));
        jButtonCancelButton.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        jButtonCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edelete.png"))); // NOI18N
        jButtonCancelButton.setText("wj,x.= lrkak ");
        jButtonCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelButtonMouseClicked(evt);
            }
        });
        jButtonCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelButtonActionPerformed(evt);
            }
        });

        jButtonAddRouteButton.setBackground(new java.awt.Color(0, 204, 0));
        jButtonAddRouteButton.setFont(new java.awt.Font("FMBindumathi", 1, 12)); // NOI18N
        jButtonAddRouteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eadd.png"))); // NOI18N
        jButtonAddRouteButton.setText("tl;= lrkak");
        jButtonAddRouteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddRouteButtonMouseClicked(evt);
            }
        });

        jTextFieldToatalDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToatalDistanceActionPerformed(evt);
            }
        });
        jTextFieldToatalDistance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldToatalDistanceKeyTyped(evt);
            }
        });

        jTextFieldEndPoint.setFont(new java.awt.Font("FMBindumathi", 0, 12)); // NOI18N
        jTextFieldEndPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEndPointActionPerformed(evt);
            }
        });

        jLabel2.setText("Km");

        BusTypeGroup.add(jRadioButtonAA);
        jRadioButtonAA.setText("A+");
        jRadioButtonAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAAActionPerformed(evt);
            }
        });

        BusTypeGroup.add(jRadioButtonA);
        jRadioButtonA.setText("A");

        BusTypeGroup.add(jRadioButtonB);
        jRadioButtonB.setText("B");

        BusTypeGroup.add(jRadioButtonC);
        jRadioButtonC.setText("C");

        BusTypeGroup.add(jRadioButtonD);
        jRadioButtonD.setText("D");
        jRadioButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*");

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*");

        jButton1.setText("DEMO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jButtonCancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAddRouteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(busNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(busModel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(busBrand)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(busManYear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(busType)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(busSPNote))
                                .addGap(210, 210, 210)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextFieldRouteId)
                                    .addComponent(jTextFieldStartPoint)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldToatalDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonAA)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonA)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonB)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonC)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonD))
                                    .addComponent(jTextFieldEndPoint))))))
                .addGap(0, 339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busNo)
                    .addComponent(jTextFieldRouteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busModel)
                    .addComponent(jTextFieldStartPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busBrand)
                    .addComponent(jTextFieldEndPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busManYear)
                    .addComponent(jRadioButtonAA)
                    .addComponent(jRadioButtonA)
                    .addComponent(jRadioButtonB)
                    .addComponent(jRadioButtonC)
                    .addComponent(jRadioButtonD)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busType)
                    .addComponent(jTextFieldToatalDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(busSPNote, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddRouteButton)
                    .addComponent(jButtonCancelButton)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStartPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStartPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStartPointActionPerformed

    private void jTextFieldRouteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRouteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRouteIdActionPerformed

    private void jTextFieldToatalDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToatalDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldToatalDistanceActionPerformed

    private void jTextFieldEndPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEndPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEndPointActionPerformed

    private void jButtonCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelButtonActionPerformed

    private void jButtonCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelButtonMouseClicked

        RouteIdSide rs = RouteIdSide.getobj();
        RouteIdTop rt = RouteIdTop.getobj();
        RouteIdMain rm = RouteIdMain.getobj();
        AddNewRouteId er = AddNewRouteId.getobj();

        rt.setVisible(true);
        rm.setVisible(true);
        rs.setVisible(true);
        er.setVisible(false);
        Temp t = Temp.temp1;
        t.upsetpanel.add(rt, t.cup);
        t.mainsetpanel.add(rm, t.cmain);
        t.sidesetpanel.add(rs, t.cside);

        //setDefalt
        jTextFieldRouteId.setText("");
        jTextFieldStartPoint.setText("");
        jTextFieldEndPoint.setText("");
        jTextFieldToatalDistance.setText("");
        jTextAreaSpNotes.setText("");
    }//GEN-LAST:event_jButtonCancelButtonMouseClicked

    private void jButtonAddRouteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddRouteButtonMouseClicked
        try {
            jRadioButtonAA.setActionCommand("A+");
            jRadioButtonA.setActionCommand("A");
            jRadioButtonB.setActionCommand("B");
            jRadioButtonC.setActionCommand("C");
            jRadioButtonD.setActionCommand("D");

            RouteIdSide rs = RouteIdSide.getobj();
            RouteIdTop rt = RouteIdTop.getobj();
            RouteIdMain rm = RouteIdMain.getobj();
            AddNewRouteId er = AddNewRouteId.getobj();

            //values pass to db
            String tbName = "rout";
            String ColumnsList = "RoutId,StartPoint,EndPoint,BusTypeList,Distance,SpNote";
            String c = "'" + jTextFieldRouteId.getText() + "','" + jTextFieldStartPoint.getText() + "','" + jTextFieldEndPoint.getText() + "','" + BusTypeGroup.getSelection().getActionCommand() + "','" + jTextFieldToatalDistance.getText() + "','" + jTextAreaSpNotes.getText() + "'";
            //System.out.println(c);
            int x = DBCon.InsertToDb(tbName, ColumnsList, c);

            if (x == 99) {
                JLabel label = new JLabel(";re i,l=Kq iys; fldgia mqrjkak ");
                label.setFont(new Font("FMBindumathi", Font.BOLD, 18));
                JOptionPane jOptionPane = new JOptionPane();
                jOptionPane.setMessage(label);
                jOptionPane.setMessage(label);
                jOptionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                JDialog dialog = jOptionPane.createDialog(null, "Error");
                dialog.setVisible(true);
                BusRegistationSide brs = BusRegistationSide.getobj();
                BusRegistationTop brt = BusRegistationTop.getobj();
                BusRegistationMain brm = BusRegistationMain.getobj();
                AddNewBus addNewBus = AddNewBus.getobj();

                rt.setVisible(false);
                rm.setVisible(false);
                rs.setVisible(false);
                er.setVisible(true);
                Temp t = Temp.temp1;
                t.upsetpanel.add(rt, t.cup);
                t.mainsetpanel.add(rm, t.cmain);
                t.sidesetpanel.add(rs, t.cside);
            } else {
                rt.setVisible(true);
                rm.setVisible(true);
                rs.setVisible(true);
                er.setVisible(false);
                Temp t = Temp.temp1;
                t.upsetpanel.add(rt, t.cup);
                t.mainsetpanel.add(rm, t.cmain);
                t.sidesetpanel.add(rs, t.cside);

                //setDefault
                jTextFieldRouteId.setText("");
                jTextFieldStartPoint.setText("");
                jTextFieldEndPoint.setText("");
                jTextFieldToatalDistance.setText("");
                jTextAreaSpNotes.setText("");
//reloard maiin ui
                rm.loadTable();
            }
        } catch (Exception e) {
            JLabel label = new JLabel(";re i,l=Kq iys; fldgia mqrjkak ");
            label.setFont(new Font("FMBindumathi", Font.BOLD, 18));
            JOptionPane jOptionPane = new JOptionPane();
            jOptionPane.setMessage(label);
            jOptionPane.setMessage(label);
            jOptionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = jOptionPane.createDialog(null, "Error");
            dialog.setVisible(true);
            BusRegistationSide brs = BusRegistationSide.getobj();
            BusRegistationTop brt = BusRegistationTop.getobj();
            BusRegistationMain brm = BusRegistationMain.getobj();
            AddNewBus addNewBus = AddNewBus.getobj();

            RouteIdSide rs = RouteIdSide.getobj();
            RouteIdTop rt = RouteIdTop.getobj();
            RouteIdMain rm = RouteIdMain.getobj();
            AddNewRouteId er = AddNewRouteId.getobj();

            rt.setVisible(false);
            rm.setVisible(false);
            rs.setVisible(false);
            er.setVisible(true);
            Temp t = Temp.temp1;
            t.upsetpanel.add(rt, t.cup);
            t.mainsetpanel.add(rm, t.cmain);
            t.sidesetpanel.add(rs, t.cside);

        }
    }//GEN-LAST:event_jButtonAddRouteButtonMouseClicked

    private void jRadioButtonAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAAActionPerformed

    private void jTextFieldToatalDistanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldToatalDistanceKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c) && !evt.isAltDown()) {
            evt.consume();
            JLabel label = new JLabel("wkal muKla w;=,alrkak ");
            label.setFont(new Font("FMBindumathi", Font.BOLD, 18));
            JOptionPane jOptionPane = new JOptionPane();
            jOptionPane.setMessage(label);

            jOptionPane.setMessage("Select Row");
            jOptionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = jOptionPane.createDialog(null, "Error");
            dialog.setVisible(true);
        }
        String len = jTextFieldToatalDistance.getText();
        int x = len.length();
        if (x >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldToatalDistanceKeyTyped

    private void jRadioButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jTextFieldRouteId.setText("57");
        jTextFieldStartPoint.setText("jõkshdj");
        jTextFieldEndPoint.setText("fld<U");
        jTextFieldToatalDistance.setText("250");
        jTextAreaSpNotes.setText("");

        jRadioButtonAA.setActionCommand("A+");
        jRadioButtonA.setActionCommand("A");
        jRadioButtonB.setActionCommand("B");
        jRadioButtonC.setActionCommand("C");
        jRadioButtonD.setActionCommand("D");
        
        BusTypeGroup.setSelected(jRadioButtonA.getModel(), true);


    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BusTypeGroup;
    private javax.swing.JLabel busBrand;
    private javax.swing.JLabel busManYear;
    private javax.swing.JLabel busModel;
    private javax.swing.JLabel busNo;
    private javax.swing.JLabel busSPNote;
    private javax.swing.JLabel busType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddRouteButton;
    private javax.swing.JButton jButtonCancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonAA;
    private javax.swing.JRadioButton jRadioButtonB;
    private javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JRadioButton jRadioButtonD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSpNotes;
    private javax.swing.JTextField jTextFieldEndPoint;
    private javax.swing.JTextField jTextFieldRouteId;
    private javax.swing.JTextField jTextFieldStartPoint;
    private javax.swing.JTextField jTextFieldToatalDistance;
    // End of variables declaration//GEN-END:variables
}
