/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_sachin.panel;

import SLTB_sachin.Class.Duty;
import SLTB_sachin.Class.Toast;
import SLTB_sachin.Temp;
import java.awt.Window;

/**
 *
 * @author sachin kumara
 */
public class Duty_list_up extends javax.swing.JPanel {

    private Duty_list duty_list = null;
    private static Duty_list_up duty_list_up = null;

    /**
     * Creates new form Duty_list_up
     */
    private Duty_list_up() {
        initComponents();
    }

    public static Duty_list_up getobj() {
        if (duty_list_up == null) {
            duty_list_up = new Duty_list_up();
        }
        return duty_list_up;
    }

    public void checkDutyno(int tf) {
        //only INT numbes for duty number
        String val = dutyno.getText();
        int len = val.length();
        if (!Duty_list.getobj().isINT(val)) {
            if (len == 1 || len == 0) {
                dutyno.setText("");
            } else {
                dutyno.setText(val.substring(0, len - 1));
            }
            if(tf==0){
                
                Window w[]=Temp.getWindows();
                 Toast.showtoast("mQ¾K ixLHd muKla ndú;d lrkak",w[0]);
            }
        }
        SearchDutyno();
    }

    public void Search() {
        if ((service_s.getText().equalsIgnoreCase("") || service_s.getText() == null) && (service_m.getText().equalsIgnoreCase("") || service_m.getText() == null) && (service_e.getText().equalsIgnoreCase("") || service_e.getText() == null)) {
            duty_list = Duty_list.getobj();
            duty_list.loadtable();

        } else {
            String ss, sm, se;
            ss = service_s.getText();
            sm = service_m.getText();
            se = service_e.getText();

            Duty d = new Duty();
            duty_list = Duty_list.getobj();
            duty_list.setRe(d.Search(ss, sm, se));
            duty_list.setTable();

        }

    }

    public void SearchDutyno() {
        if (dutyno.getText().equalsIgnoreCase("") || dutyno.getText() == null) {
            duty_list = Duty_list.getobj();
            duty_list.loadtable();

        } else {
            int no = Integer.valueOf(dutyno.getText());
            Duty d = new Duty();
            duty_list = Duty_list.getobj();
            duty_list.setRe(d.SearchDutyno(no));
            duty_list.setTable();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        service_e = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dutyno = new javax.swing.JTextField();
        service_s = new javax.swing.JTextField();
        service_m = new javax.swing.JTextField();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 60));

        jLabel1.setFont(new java.awt.Font("FMBindumathi", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/esearch.png"))); // NOI18N
        jLabel1.setText("fidhkak ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel2.setText("ld¾h wxlh ");

        service_e.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        service_e.setMaximumSize(new java.awt.Dimension(14, 32));
        service_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                service_eMouseClicked(evt);
            }
        });
        service_e.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                service_eKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                service_eKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel3.setText("fiajdj wdrïNh$ueo$wjidkh  ");

        dutyno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dutyno.setMaximumSize(new java.awt.Dimension(14, 32));
        dutyno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dutynoMouseClicked(evt);
            }
        });
        dutyno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dutynoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dutynoKeyTyped(evt);
            }
        });

        service_s.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        service_s.setMaximumSize(new java.awt.Dimension(14, 32));
        service_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                service_sMouseClicked(evt);
            }
        });
        service_s.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                service_sKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                service_sKeyTyped(evt);
            }
        });

        service_m.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        service_m.setMaximumSize(new java.awt.Dimension(14, 32));
        service_m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                service_mMouseClicked(evt);
            }
        });
        service_m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                service_mKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                service_mKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dutyno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(service_s, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(service_m, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(service_e, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(service_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(service_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(service_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dutyno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dutynoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dutynoMouseClicked
        service_s.setText("");
        service_m.setText("");
        service_e.setText("");
    }//GEN-LAST:event_dutynoMouseClicked

    private void service_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_service_sMouseClicked
        dutyno.setText("");
    }//GEN-LAST:event_service_sMouseClicked

    private void service_mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_service_mMouseClicked
        dutyno.setText("");
    }//GEN-LAST:event_service_mMouseClicked

    private void service_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_service_eMouseClicked
        dutyno.setText("");
    }//GEN-LAST:event_service_eMouseClicked

    private void dutynoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dutynoKeyTyped
        checkDutyno(1);
    }//GEN-LAST:event_dutynoKeyTyped

    private void dutynoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dutynoKeyReleased
        checkDutyno(0);
    }//GEN-LAST:event_dutynoKeyReleased

    private void service_sKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_sKeyReleased
        Search();
    }//GEN-LAST:event_service_sKeyReleased

    private void service_sKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_sKeyTyped
        Search();
    }//GEN-LAST:event_service_sKeyTyped

    private void service_mKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_mKeyReleased
        Search();
    }//GEN-LAST:event_service_mKeyReleased

    private void service_mKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_mKeyTyped
        Search();
    }//GEN-LAST:event_service_mKeyTyped

    private void service_eKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_eKeyReleased
        Search();
    }//GEN-LAST:event_service_eKeyReleased

    private void service_eKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_eKeyTyped
        Search();
    }//GEN-LAST:event_service_eKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dutyno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField service_e;
    private javax.swing.JTextField service_m;
    private javax.swing.JTextField service_s;
    // End of variables declaration//GEN-END:variables
}
