/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_sachin.panel;

import SLTB_sachin.Class.Monthly_duty;
import SLTB_sachin.Class.Toast;
import SLTB_sachin.Temp;
import java.awt.Window;

/**
 *
 * @author sachin kumara
 */
public class Monthly_duty_up extends javax.swing.JPanel {

    private static Monthly_duty_up mdup = null;
    private Monthly_duty md = new Monthly_duty();

    /**
     * Creates new form monthly_duty_up
     */
    private Monthly_duty_up() {
        initComponents();
    }

    public static Monthly_duty_up getobj() {
        if (mdup == null) {
            mdup = new Monthly_duty_up();
        }
        return mdup;
    }

    public void checksalyno(int tf) {
        //only INT numbes for duty number
        String val = sal_no.getText();
        int len = val.length();
        if (!isINT(val)) {
            if (len == 1 || len == 0) {
                sal_no.setText("");
                serch();
            } else {
                sal_no.setText(val.substring(0, len - 1));
            }
            if(tf==0){
                
                Window w[]=Temp.getWindows();
                 Toast.showtoast("ixLHd muKla ndú;d lrkak",w[0]);
            }
        } else {
            serch();
        }

    }

    public void checkDutyno(int tf) {
        //only INT numbes for duty number
        String val = Duty_no.getText();
        int len = val.length();
        if (!isINT(val)) {
            if (len == 1 || len == 0) {
                Duty_no.setText("");
                serch();
            } else {
                Duty_no.setText(val.substring(0, len - 1));
            }
            if(tf==0){
                
                Window w[]=Temp.getWindows();
                 Toast.showtoast("mQ¾K ixLHd muKla ndú;d lrkak",w[0]);
            }
        } else {
            serch();
        }

    }

    public boolean isINT(String strNum) {
        boolean ret = true;
        try {

            Integer.valueOf(strNum);

        } catch (NumberFormatException e) {
            ret = false;
        }
        return ret;
    }

    public void tfclean() {
        bus_no.setText("");
        sal_no.setText("");
        Duty_no.setText("");
    }

    public void serch() {
        String b = bus_no.getText();
        String d = Duty_no.getText();
        String s = sal_no.getText();
        if (b.equalsIgnoreCase("") && d.equalsIgnoreCase("") && s.equalsIgnoreCase("")) {
            Monthly_duty_main.getobj().loadtable(Integer.valueOf(mon_s.getSelectedItem().toString()), Integer.valueOf(year_s.getSelectedItem().toString()));

        } else {
            String m = mon_s.getSelectedItem().toString();
            String y = year_s.getSelectedItem().toString();
            Monthly_duty_main.getobj().serch(md.search(m, y, b, s, d));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        year = new javax.swing.JLabel();
        mon = new javax.swing.JLabel();
        mon_s = new javax.swing.JComboBox<>();
        year_s = new javax.swing.JComboBox<>();
        year1 = new javax.swing.JLabel();
        bus_no = new javax.swing.JTextField();
        year2 = new javax.swing.JLabel();
        sal_no = new javax.swing.JTextField();
        year3 = new javax.swing.JLabel();
        Duty_no = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 60));

        year.setFont(new java.awt.Font("FMBindumathi", 1, 24)); // NOI18N
        year.setText("wjqreoao");

        mon.setFont(new java.awt.Font("FMBindumathi", 1, 24)); // NOI18N
        mon.setText("udih");

        mon_s.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mon_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        mon_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mon_sActionPerformed(evt);
            }
        });

        year_s.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        year_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));
        year_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_sActionPerformed(evt);
            }
        });

        year1.setFont(new java.awt.Font("FMBindumathi", 1, 24)); // NOI18N
        year1.setText("nia r: wxlh ");

        bus_no.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bus_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bus_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bus_noKeyTyped(evt);
            }
        });

        year2.setFont(new java.awt.Font("FMBindumathi", 1, 24)); // NOI18N
        year2.setText("fÉ;k wxlh ");

        sal_no.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sal_no.setAutoscrolls(false);
        sal_no.setMaximumSize(new java.awt.Dimension(14, 32));
        sal_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sal_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sal_noKeyTyped(evt);
            }
        });

        year3.setFont(new java.awt.Font("FMBindumathi", 1, 24)); // NOI18N
        year3.setText("ld¾h wxlh ");

        Duty_no.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Duty_no.setMaximumSize(new java.awt.Dimension(14, 32));
        Duty_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Duty_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Duty_noKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(year)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year_s, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mon_s, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bus_no, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sal_no, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Duty_no, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year)
                    .addComponent(mon_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mon)
                    .addComponent(year_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year1)
                    .addComponent(bus_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year2)
                    .addComponent(sal_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year3)
                    .addComponent(Duty_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/esearch.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mon_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mon_sActionPerformed
        Monthly_duty_main.getobj().loadtable(Integer.valueOf(mon_s.getSelectedItem().toString()), Integer.valueOf(year_s.getSelectedItem().toString()));
        tfclean();
        Monthly_duty_main.getobj().id = null;
    }//GEN-LAST:event_mon_sActionPerformed

    private void sal_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sal_noKeyReleased
        checksalyno(0);
    }//GEN-LAST:event_sal_noKeyReleased

    private void sal_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sal_noKeyTyped
        checksalyno(1);
    }//GEN-LAST:event_sal_noKeyTyped

    private void Duty_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Duty_noKeyReleased
        checkDutyno(0);
    }//GEN-LAST:event_Duty_noKeyReleased

    private void Duty_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Duty_noKeyTyped
        checkDutyno(1);
    }//GEN-LAST:event_Duty_noKeyTyped

    private void year_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_sActionPerformed
        Monthly_duty_main.getobj().loadtable(Integer.valueOf(mon_s.getSelectedItem().toString()), Integer.valueOf(year_s.getSelectedItem().toString()));
        tfclean();
        Monthly_duty_main.getobj().id = null;
    }//GEN-LAST:event_year_sActionPerformed

    private void bus_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bus_noKeyReleased
        serch();
    }//GEN-LAST:event_bus_noKeyReleased

    private void bus_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bus_noKeyTyped
        serch();
    }//GEN-LAST:event_bus_noKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Duty_no;
    private javax.swing.JTextField bus_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mon;
    public static javax.swing.JComboBox<String> mon_s;
    private javax.swing.JTextField sal_no;
    private javax.swing.JLabel year;
    private javax.swing.JLabel year1;
    private javax.swing.JLabel year2;
    private javax.swing.JLabel year3;
    public static javax.swing.JComboBox<String> year_s;
    // End of variables declaration//GEN-END:variables
}
