/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_ghost.security;

import com.ConnectionMysql.MysqlConnect;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author GHOST
 */
public class depot_vehicle extends javax.swing.JPanel {
private static depot_vehicle depot_vehicleS=null;

    /**
     * Creates new form depot_vehicle
     */
    public depot_vehicle() {
        initComponents();
    }
     public static depot_vehicle getobj(){
        if(depot_vehicleS==null){
            depot_vehicleS=new depot_vehicle();
        }
        return depot_vehicleS;
    }
         public void dtable(){
         try{
    depotTable.getTableHeader().setFont(new Font("FMBindumathi", Font.BOLD, 18));
   
   
            
             Connection conn=MysqlConnect.getDbCon();

            String query="select * from depot_vehicle" ;
                    Statement stmt= conn.createStatement();
                    ResultSet rs=stmt.executeQuery(query);
                    depotTable.setModel(DbUtils.resultSetToTableModel(rs));
                    
depotTable.getColumn("ID").setHeaderValue("wxlh ");
depotTable.getColumn("license_number").setHeaderValue("jdyk wxlh ");
depotTable.getColumn("v_time").setHeaderValue("fj,dj");
depotTable.getColumn("v_come_leave").setHeaderValue("meñKSu$msg;a ùu");
depotTable.getColumn("v_date").setHeaderValue("oji");



depotTable.repaint();

                  
        }catch(Exception e){
            
        }

}  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        license_number = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        depotTable = new javax.swing.JTable();
        v_come_leave = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        dlicense_number = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1149, 710));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1149, 710));

        jLabel2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel2.setText("jdyk ,shdmosxÑ wxlh ");

        license_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                license_numberActionPerformed(evt);
            }
        });

        depotTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(depotTable);

        v_come_leave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v_come_leave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Come in", "Leave" }));
        v_come_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_come_leaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel1.setText("meñKSu$msg;a ùu");

        dlicense_number.setFont(new java.awt.Font("FMBindumathi", 1, 11)); // NOI18N
        dlicense_number.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setText("demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButton1)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v_come_leave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(license_number, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlicense_number, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(license_number, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlicense_number, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_come_leave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void v_come_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_come_leaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_come_leaveActionPerformed

    private void license_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_license_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_license_numberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               license_number.setText("AB-7898"); 
              
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable depotTable;
    public javax.swing.JLabel dlicense_number;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField license_number;
    public javax.swing.JComboBox<String> v_come_leave;
    // End of variables declaration//GEN-END:variables
}
