/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_login;

import SLTB_login.MainPanels.AdminMain;
import SLTB_login.MainPanels.DutyOperationMain;
import SLTB_login.MainPanels.EmployeeMain;
import SLTB_login.MainPanels.FinancialMain;
import SLTB_login.MainPanels.FuelRepairMain;
import SLTB_login.MainPanels.SecurityMain;
import SLTB_login.MainPanels.SupplierMain;
import SLTB_sachin.Temp;
import com.ConnectionMysql.MysqlConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Chamika Prabath
 */
public class Login extends javax.swing.JPanel {
private static Login log=null;
public static String logGrade;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        c1.setVisible(false);
        c2.setVisible(false);
    }

    public static Login getobj(){
        if(log==null){
            log=new Login();
        }
        return log;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1149, 710));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1149, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel1.setText("cd;sl yeÿkqïm;a wxlh ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 220, 35));

        jLabel2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel2.setText("uqr moh  ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 142, 51));

        nic.setToolTipText("Enter NIC");
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 239, 43));

        login.setBackground(new java.awt.Color(153, 255, 153));
        login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 120, 40));

        password.setToolTipText("Enter Password");
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 239, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginPic.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 176, 164));

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ecorre.png"))); // NOI18N
        add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, -1, 39));

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ecorre.png"))); // NOI18N
        add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, 38));

        reset.setBackground(new java.awt.Color(255, 153, 153));
        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset");
        reset.setToolTipText("");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
         
     try {	/*calling the mysql connection class*/
             Login log=Login .getobj();
             Temp tmp=Temp.temp1;
             Connection conn=MysqlConnect.getDbCon();
             String Nic=nic.getText();
             String pass=password.getText();
             String query="select count(SalaryNo),E_Grade from Employee where E_NIC='"+Nic+"' and E_Password='"+pass+"'" ;
                    Statement stmt= conn.createStatement();
                    ResultSet rs=stmt.executeQuery(query);
                    while(rs.next()){
                        
                     int i=rs.getInt("count(SalaryNo)");
                     logGrade=rs.getString("E_Grade");
                     if(i==1){
                         if("HR Clerk".equals(logGrade)){
                              EmployeeMain EmpM=EmployeeMain .getobj();
                              EmpM.setVisible(true);
                              log.setVisible(false);
                              tmp.mainsetpanel.add(EmpM,tmp.cmain);
                         }else if("A.M Operarion".equals(logGrade)){
                              DutyOperationMain dutyM=DutyOperationMain .getobj();
                              dutyM.setVisible(true);
                              log.setVisible(false);
                              tmp.mainsetpanel.add(dutyM,tmp.cmain);
                         }else if("A.M Security".equals(logGrade)){
                              SecurityMain secM=SecurityMain .getobj();
                              secM.setVisible(true);
                              log.setVisible(false);
                              tmp.mainsetpanel.add(secM,tmp.cmain);
                         }else if("Inventory Clerk".equals(logGrade)){
                              SupplierMain supM=SupplierMain .getobj();
                              supM.setVisible(true);
                              log.setVisible(false);
                              tmp.mainsetpanel.add(supM,tmp.cmain);
                         }else if("A.M Engineering".equals(logGrade)){
                              FuelRepairMain FRM=FuelRepairMain .getobj();
                              FRM.setVisible(true);
                              log.setVisible(false);
                              tmp.mainsetpanel.add(FRM,tmp.cmain);
                         }else if("A.M Financial".equals(logGrade)){
                              FinancialMain finM=FinancialMain .getobj();
                              finM.setVisible(true);
                              log.setVisible(false);
                              tmp.mainsetpanel.add(finM,tmp.cmain);
                         }else if("Manager".equals(logGrade)){
                              AdminMain adM=AdminMain .getobj();
                              adM.setVisible(true);
                              log.setVisible(false);
                              tmp.mainsetpanel.add(adM,tmp.cmain);
                         }
                         
                     }else{
                         showMessage("Invalid User");
                   System.out.println("Invalid User"); 
                     }
            
            
                    }
        } catch (Exception e) {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_loginMouseClicked

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        // TODO add your handling code here:
        try {	/*calling the mysql connection class*/

            Connection conn=MysqlConnect.getDbCon();
            String Nic=nic.getText();
            String pass=password.getText();
            String query="select count(SalaryNo) from Employee where E_NIC='"+Nic+"'" ;
            Statement stmt= conn.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){

                int i=rs.getInt("count(SalaryNo)");

                if(i==1){
                    c1.setVisible(true);

                }else{
                    c1.setVisible(false);
                }

            }
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_nicKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        try {	/*calling the mysql connection class*/

            Connection conn=MysqlConnect.getDbCon();
            String Nic=nic.getText();
            String pass=password.getText();
            String query="select count(SalaryNo) from Employee where E_NIC='"+Nic+"' and E_Password='"+pass+"'" ;
            Statement stmt= conn.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){

                int i=rs.getInt("count(SalaryNo)");

                if(i==1){
                    c2.setVisible(true);

                }else{
                    c2.setVisible(false);
                }

            }
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_passwordKeyReleased

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
         nic.setText("");
         password.setText("");
        
    }//GEN-LAST:event_resetActionPerformed
 private void showMessage(String text) {
		JOptionPane.showMessageDialog(null, text);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel c1;
    public javax.swing.JLabel c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    public javax.swing.JTextField nic;
    public javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
