/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_login.MainPanels;

import SLTB_Bimsara.Oparation.OparationMain;
import SLTB_Bimsara.Oparation.OparationSide;
import SLTB_Bimsara.Oparation.OparationTop;
import SLTB_Bimsara.Panel.BusRegistation.BusRegistationMain;
import SLTB_Bimsara.Panel.BusRegistation.BusRegistationSide;
import SLTB_Bimsara.Panel.BusRegistation.BusRegistationTop;
import SLTB_Bimsara.Route.RouteIdMain;
import SLTB_Bimsara.Route.RouteIdSide;
import SLTB_Bimsara.Route.RouteIdTop;
import SLTB_sachin.Temp;
import SLTB_sachin.panel.Daily_duty_main;
import SLTB_sachin.panel.Duty_list;
import SLTB_sachin.panel.Monthly_duty_main;

/**
 *
 * @author Chamika Prabath
 */
public class DutyOperationMain extends javax.swing.JPanel {
private static DutyOperationMain dutyM=null;
    /**
     * Creates new form DutyMain
     */
    public DutyOperationMain() {
        initComponents();
    }

    public static DutyOperationMain getobj(){
        if(dutyM==null){
            dutyM=new DutyOperationMain();
        }
        return dutyM;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1149, 710));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1149, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dutyMan.png"))); // NOI18N
        jLabel1.setToolTipText("Manage Duty");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dailyDuty.png"))); // NOI18N
        jLabel2.setToolTipText("Manage Daily Duty");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monthluDuty.png"))); // NOI18N
        jLabel3.setToolTipText("Manage Monthly Duty");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel5.setText("udisl ld¾hh l<ukdlrKh ");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel6.setText("ld¾hh l<ukdlrKh ");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel7.setText("ffoksl ld¾hh l<ukdlrKh ");
        jLabel7.setToolTipText("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/routeReg.png"))); // NOI18N
        jLabel4.setToolTipText("Manage Routes");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel8.setText("ud¾. l<ukdlrKh ");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel9.setText("fufyhqï l<ukdlrKh ");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel10.setText("nia r: l<ukdlrKh ");
        jLabel10.setToolTipText("");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/operationM.png"))); // NOI18N
        jLabel11.setToolTipText("Manage Operations");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busReg.png"))); // NOI18N
        jLabel12.setToolTipText("Manage Buses");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel12)
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(53, 53, 53)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2))
                            .addComponent(jLabel7))
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3))
                    .addComponent(jLabel5))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11))
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(215, 215, 215))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         SLTB_sachin.Temp te = Temp.temp1;
        Duty_list dul = Duty_list.getobj();
        dul.setVisible(true);
        te.mainsetpanel.add(dul, te.cmain);
        this.setVisible(false);
        Duty_list.getobj().setnew();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        SLTB_sachin.Temp te = Temp.temp1;
        Daily_duty_main ddu = Daily_duty_main.getobj();
        ddu.setVisible(true);
        te.mainsetpanel.add(ddu, te.cmain);
        this.setVisible(false);
        Daily_duty_main.getobj().setnew();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         SLTB_sachin.Temp te = Temp.temp1;
        Monthly_duty_main mdu = Monthly_duty_main.getobj();
        mdu.setVisible(true);
        te.mainsetpanel.add(mdu, te.cmain);
        this.setVisible(false);
        Monthly_duty_main.getobj().setnew();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        DutyOperationMain dutyM = DutyOperationMain.getobj();
        RouteIdSide rs=RouteIdSide.getobj();
        RouteIdTop rt=RouteIdTop.getobj();
        RouteIdMain rm=RouteIdMain.getobj();
        
                
        rt.setVisible(true);
        rm.setVisible(true);
        rs.setVisible(true);
        dutyM.setVisible(false);
        Temp t=Temp.temp1;
        t.upsetpanel.add(rt,t.cup);
        t.mainsetpanel.add(rm,t.cmain);
        t.sidesetpanel.add(rs,t.cside);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        DutyOperationMain dutyM = DutyOperationMain.getobj();
        OparationSide os = OparationSide.getobj();
        OparationTop ot = OparationTop.getobj();
        OparationMain om = OparationMain.getobj();

        dutyM.setVisible(false);
        os.setVisible(true);
        ot.setVisible(true);
        om.setVisible(true);
        Temp t = Temp.temp1;
        t.upsetpanel.add(ot, t.cup);
        t.mainsetpanel.add(om, t.cmain);
        t.sidesetpanel.add(os, t.cside);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        DutyOperationMain dutyM = DutyOperationMain.getobj();
        BusRegistationTop brt = BusRegistationTop.getobj();
        BusRegistationMain brm = BusRegistationMain.getobj();
        BusRegistationSide brs = BusRegistationSide.getobj();

        dutyM.setVisible(false);
        brt.setVisible(true);
        brm.setVisible(true);
        brs.setVisible(true);
        Temp t = Temp.temp1;
        t.upsetpanel.add(brt, t.cup);
        t.mainsetpanel.add(brm, t.cmain);
        t.sidesetpanel.add(brs, t.cside);
    }//GEN-LAST:event_jLabel12MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
