/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_login.MainPanels;

import SLTB_chamika.employee.ManageAttendance;
import SLTB_chamika.employee.ManageAttendanceUp;
import SLTB_chamika.employee.ManageEmployee;
import SLTB_chamika.employee.ManageEmployeeUp;
import SLTB_chamika.employee.ManageLeave;
import SLTB_chamika.employee.ManageLeaveSide;
import SLTB_chamika.employee.ManageLeaveUp;
import SLTB_chamika.employee.Webcam;
import SLTB_sachin.Temp;



/**
 *
 * @author Chamika Prabath
 */
public class EmployeeMain extends javax.swing.JPanel {
private static EmployeeMain employeeM=null;
    /**
     * Creates new form EmployeeMain
     */
    public EmployeeMain() {
        initComponents();
    }

    public static EmployeeMain getobj(){
        if(employeeM==null){
            employeeM=new EmployeeMain();
        }
        return employeeM;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setToolTipText("Manage Leaves");
        setMaximumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1149, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manageEmployee.png"))); // NOI18N
        jLabel1.setToolTipText("Manage Emplyee Details");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel2.setText("ksjdvq l,ukdlrkh ");
        jLabel2.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leaves.png"))); // NOI18N
        jLabel3.setToolTipText("Manage Leaves");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atten.png"))); // NOI18N
        jLabel4.setToolTipText("Manage Attendance");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel5.setText("fiajl l<ukdlrKh ");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel6.setText("meñKSu l,ukdlrkh ");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jLabel5)
                    .addContainerGap(872, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(472, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(201, 201, 201)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(471, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        EmployeeMain employeeM=EmployeeMain.getobj();
        ManageEmployee manageE=ManageEmployee.getobj();
        ManageEmployeeUp manageEup=ManageEmployeeUp.getobj();

        employeeM.setVisible(false);
        manageE.setVisible(true);
        manageEup.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(manageE,tmp.cmain);
        tmp.upsetpanel.add(manageEup,tmp.cup);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        EmployeeMain employeeM=EmployeeMain.getobj();
        ManageLeave manageL=ManageLeave.getobj();
        ManageLeaveUp manageLup=ManageLeaveUp.getobj();
        ManageLeaveSide manageLside=ManageLeaveSide.getobj();
        
        manageL.TableLoad1();
        manageL.TableLoad2();
        employeeM.setVisible(false);
        manageL.setVisible(true);
        manageLup.setVisible(true);
        manageLside.setVisible(true);
        
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(manageL,tmp.cmain);
        tmp.upsetpanel.add(manageLup,tmp.cup);
        tmp.sidesetpanel.add(manageLside,tmp.cside);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        EmployeeMain employeeM=EmployeeMain.getobj();
        Webcam wc=Webcam.getobj();
        ManageAttendance manageA=ManageAttendance.getobj();
        ManageAttendanceUp manageAup=ManageAttendanceUp.getobj();
        manageA.TableLoad1();
        manageA.TableLoad2();

        employeeM.setVisible(false);
        wc.setVisible(true);
        manageA.setVisible(true);
        manageAup.setVisible(true);
        Temp tmp=Temp.temp1;
        
        tmp.sidesetpanel.add(wc,tmp.cside);
        tmp.mainsetpanel.add(manageA,tmp.cmain);
        tmp.upsetpanel.add(manageAup,tmp.cup);
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
