/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_login.MainPanels;

import SLTB_sachin.Temp;

import SLTB_sandu.fuel.fueL1;
import SLTB_sandu.fuel.stock;
import SLTB_sandu.fuel.waste;
import SLTB_wishva.repair.S_stock;
import SLTB_wishva.repair.Stock_up;
import SLTB_wishva.repair.avil;
import SLTB_wishva.repair.avil_up;
import SLTB_wishva.repair.busrepair;
import SLTB_wishva.repair.part_up;
import SLTB_wishva.repair.parts;
import SLTB_wishva.repair.rep_up;


/**
 *
 * @author Chamika Prabath
 */
public class FuelRepairMain extends javax.swing.JPanel {
private static FuelRepairMain FRM=null;
    /**
     * Creates new form RepairMain
     */
    public FuelRepairMain() {
        initComponents();
    }

     public static FuelRepairMain getobj(){
        if(FRM==null){
            FRM=new FuelRepairMain();
        }
        return FRM;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1149, 710));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1149, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busRep.png"))); // NOI18N
        jLabel1.setToolTipText("Bus Repair");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stockManage.png"))); // NOI18N
        jLabel2.setToolTipText("Repair Stock");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/availBus.png"))); // NOI18N
        jLabel3.setToolTipText("Available Busses");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel6.setText("wu;r fldgia .nvdj  ");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel7.setText("nia r: w¨;ajeähdj ");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel8.setText("Nú;d l, yels nia r: ");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel9.setText("wu;r fldgia ");
        jLabel9.setToolTipText("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spareParts.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel11.setText("bkaOk .nvdj");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel12.setText("bkaOk ksl=;a lsÍu ");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel13.setText("bj; ouk ødjK  ");
        jLabel13.setToolTipText("");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fuelWaste.png"))); // NOI18N
        jLabel14.setToolTipText("");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fuelStock.png"))); // NOI18N
        jLabel15.setToolTipText("Fuel Stock");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fuelRelease.png"))); // NOI18N
        jLabel16.setToolTipText("Fuel Release");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11))
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel16)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1))
                            .addComponent(jLabel7))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(153, 153, 153)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel9)))
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(77, 77, 77))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       FuelRepairMain frM=FuelRepairMain.getobj();     
       busrepair te02=busrepair.getobj();
        
        frM.setVisible(false);
        te02.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(te02,tmp.cmain); 
        
         rep_up te03= rep_up.getobj();
        
       
         te03.setVisible(true);
        
        
        tmp.upsetpanel.add(te03,tmp.cup);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         FuelRepairMain frM=FuelRepairMain.getobj();        
       S_stock te02= S_stock.getobj();
        
       frM.setVisible(false);
        te02.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(te02,tmp.cmain); 
        Stock_up te03= Stock_up.getobj();
        
         te03.setVisible(true);
        
        tmp.upsetpanel.add(te03,tmp.cup);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        FuelRepairMain frM=FuelRepairMain.getobj();          
       avil te02= avil.getobj();
        
        frM.setVisible(false);
        te02.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(te02,tmp.cmain);
           tmp.mainsetpanel.add(te02,tmp.cmain);
        
          avil_up te03=  avil_up.getobj();
        
       
         te03.setVisible(true);
        
        
        tmp.upsetpanel.add(te03,tmp.cup);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         FuelRepairMain frM=FuelRepairMain.getobj();       
       parts te02= parts.getobj();
        
        frM.setVisible(false);
        te02.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(te02,tmp.cmain);
        
          part_up te03= part_up.getobj();
        
         te03.setVisible(true);
        
        tmp.upsetpanel.add(te03,tmp.cup);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        FuelRepairMain.getobj().setVisible(false);
        
        waste te02 = waste.getobj();

        te02.setVisible(true);

        Temp tmp = Temp.temp1;
        tmp.mainsetpanel.add(te02, tmp.cmain);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        FuelRepairMain.getobj().setVisible(false);
        stock te02 = stock.getobj();
        //search te03 = search.getobj();

        te02.setVisible(true);
       
        Temp tmp = Temp.temp1;
        tmp.mainsetpanel.add(te02, tmp.cmain);
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
       FuelRepairMain.getobj().setVisible(false);
        fueL1 te02 = fueL1.getobj();

        te02.setVisible(true);
        Temp tmp = Temp.temp1;
        tmp.mainsetpanel.add(te02, tmp.cmain);
    }//GEN-LAST:event_jLabel16MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
