/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_login.MainPanels;

import SLTB_ghost.security.button1;
import SLTB_ghost.security.button2;
import SLTB_ghost.security.button3;
import SLTB_ghost.security.button4;
import SLTB_ghost.security.depot_vehicle;
import SLTB_ghost.security.guest;
import SLTB_ghost.security.other_vehicle;
import SLTB_ghost.security.ticket_book;
import SLTB_sachin.Temp;

/**
 *
 * @author Chamika Prabath
 */
public class SecurityMain extends javax.swing.JPanel {
private static SecurityMain secM=null;
    /**
     * Creates new form SecurityMain
     */
    public SecurityMain() {
        initComponents();
    }
    
 public static SecurityMain getobj(){
        if(secM==null){
            secM=new SecurityMain();
        }
        return secM;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1149, 710));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1149, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guestSec.png"))); // NOI18N
        jLabel1.setToolTipText("Guest Registry");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/depoVehicle.png"))); // NOI18N
        jLabel2.setToolTipText("Depo Vehicle Security");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OtherVehicle.png"))); // NOI18N
        jLabel3.setToolTipText("Other Vehicle Security");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel6.setText("äfmdafõ jdyk l<ukdlrKh ");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel7.setText("wuq;a;ka l<ukdlrKh ");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel8.setText("wfkl=;a jdyk l<ukdlrKh ");
        jLabel8.setToolTipText("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ticketB.png"))); // NOI18N
        jLabel4.setToolTipText("Book Tickets");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel9.setText(" álÜm;a  fjkalsÍu ");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(435, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        SecurityMain.getobj().setVisible(false);
        guest guestS=guest.getobj();
        button1 button1G=button1.getobj();
      
        guestS.gtable();
        
        guestS.setVisible(true);
        button1G.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(guestS,tmp.cmain);
        tmp.upsetpanel.add(button1G,tmp.cup);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         SecurityMain.getobj().setVisible(false);
        depot_vehicle depot_vehicleS=depot_vehicle.getobj();
        button3 button3D=button3.getobj();

        depot_vehicleS.dtable();

        depot_vehicleS.setVisible(true);
        button3D.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(depot_vehicleS,tmp.cmain);
        tmp.upsetpanel.add(button3D,tmp.cup);    
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        SecurityMain.getobj().setVisible(false);
        other_vehicle other_vehicleS=other_vehicle.getobj();
        button2 button2O=button2.getobj();
   
        other_vehicleS.otable();

        other_vehicleS.setVisible(true);
        button2O.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(other_vehicleS,tmp.cmain);
        tmp.upsetpanel.add(button2O,tmp.cup);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         SecurityMain.getobj().setVisible(false);
        ticket_book ticket_bookS=ticket_book.getobj();
        button4 button4T=button4.getobj();
        
        ticket_bookS.ttable();
        
        ticket_bookS.setVisible(true);
        button4T.setVisible(true);
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(ticket_bookS,tmp.cmain);
        tmp.upsetpanel.add(button4T,tmp.cup); 
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
