/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_supun_panal;

import SLTB_sachin.Temp;
import com.ConnectionMysql.MysqlConnect;
import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SUPUN
 */
public class chooce_comp extends javax.swing.JPanel {

    private static chooce_comp chuce = null;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String sss;
    public static String mail=null;

    /**
     * Creates new form chooce_comp
     */
    private chooce_comp() {
        initComponents();
        con = MysqlConnect.getDbCon();

        tablelord();

        setcolfront();

    }

    public static chooce_comp getobj() {
        if (chuce == null) {
            chuce = new chooce_comp();
        }
        return chuce;
    }

    public void tablelord() {

        String sql = "SELECT cid as 'wxlh ',c_name as 'ku ',typeo as 'j¾.h ',validate_year as 'j ld,h ',phone_number as 'ÿ wx ',address as ',smskh ' ,e_maill as 'B fï,a ',validate_start_date as 'j wd osk' FROM supplier";

        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            c_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }

    public void setnew() {

        c_table.getTableHeader().setFont(new Font("FMBindumathi", Font.BOLD, 16));

        /*com_serch du= com_serch.getobj();
        SLTB_sachin.Temp te=Temp.temp1;
        du.setVisible(true);
        te.upsetpanel.add(du,te.cup);*/
    }

    public void setcolfront() {
        DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
            Font font = new Font("Calibri", Font.BOLD, 14);

            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus,
                    int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus,
                        row, column);
                setFont(font);
                return this;
            }

        };
        c_table.getColumnModel().getColumn(6).setCellRenderer(r);
        c_table.getColumnModel().getColumn(7).setCellRenderer(r);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        c_cid = new javax.swing.JTextField();
        com_edit = new javax.swing.JButton();
        com_delete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        c_cname = new javax.swing.JTextField();
        c_cpho = new javax.swing.JTextField();
        c_cperiad = new javax.swing.JTextField();
        c_cemall = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        c_caddress = new javax.swing.JTextArea();
        com_select = new javax.swing.JButton();
        com_add = new javax.swing.JButton();
        c_ctype = new javax.swing.JComboBox<>();
        com_rest = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        c_table = new javax.swing.JTable();
        show = new javax.swing.JLabel();
        sh = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel2.setText("wdh;k wxlh ");

        c_cid.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        c_cid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_cidMouseClicked(evt);
            }
        });
        c_cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cidActionPerformed(evt);
            }
        });
        c_cid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c_cidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c_cidKeyTyped(evt);
            }
        });

        com_edit.setBackground(new java.awt.Color(239, 219, 88));
        com_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eupdate.png"))); // NOI18N
        com_edit.setText("Edit");
        com_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_editMouseClicked(evt);
            }
        });
        com_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_editActionPerformed(evt);
            }
        });

        com_delete.setBackground(new java.awt.Color(255, 153, 153));
        com_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edelete.png"))); // NOI18N
        com_delete.setText("Delete");
        com_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_deleteMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel3.setText("wdh;kfh ku ");

        jLabel4.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel4.setText("j¾.h ");

        jLabel5.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel5.setText("j,x.= ld,h ");

        jLabel6.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel6.setText("ÿrl;k wxlh ");

        jLabel8.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel8.setText(",smskh ");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("E-maill");

        c_cname.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        c_cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cnameActionPerformed(evt);
            }
        });

        c_cpho.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        c_cpho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cphoActionPerformed(evt);
            }
        });
        c_cpho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c_cphoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c_cphoKeyTyped(evt);
            }
        });

        c_cperiad.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        c_cperiad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cperiadActionPerformed(evt);
            }
        });
        c_cperiad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c_cperiadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c_cperiadKeyTyped(evt);
            }
        });

        c_cemall.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        c_cemall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cemallActionPerformed(evt);
            }
        });

        c_caddress.setColumns(20);
        c_caddress.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        c_caddress.setRows(5);
        jScrollPane2.setViewportView(c_caddress);

        com_select.setBackground(new java.awt.Color(239, 219, 88));
        com_select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ecorre.png"))); // NOI18N
        com_select.setText("Select");
        com_select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_selectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                com_selectMouseEntered(evt);
            }
        });

        com_add.setBackground(new java.awt.Color(153, 255, 153));
        com_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eadd.png"))); // NOI18N
        com_add.setText("Add");
        com_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_addMouseClicked(evt);
            }
        });
        com_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_addActionPerformed(evt);
            }
        });

        c_ctype.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        c_ctype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ld¾hd,Sh Ndxv ", "bkaOk ", "fiajd Ndkav " }));
        c_ctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ctypeActionPerformed(evt);
            }
        });

        com_rest.setBackground(new java.awt.Color(255, 153, 153));
        com_rest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arefresh.png"))); // NOI18N
        com_rest.setText("Reset");
        com_rest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                com_restMouseClicked(evt);
            }
        });

        c_table.setFont(new java.awt.Font("FMBindumathi", 0, 14)); // NOI18N
        c_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "¾ÜÜ ", "ya¾ ", "mflda ", "hska ", "Êhs ", "kaÜhs ", "kakahs ", "kahs "
            }
        ));
        c_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(c_table);

        show.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(204, 0, 0));

        sh.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        sh.setForeground(new java.awt.Color(204, 0, 0));

        s.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        s.setForeground(new java.awt.Color(204, 0, 0));

        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_ctype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_cpho)
                                    .addComponent(c_cperiad)
                                    .addComponent(c_cemall)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c_cid)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_cname))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(com_select, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(com_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(com_add, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(com_rest, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_ctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_cperiad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_cpho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_cemall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(com_add, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(com_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(com_select, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(com_rest, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(com_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c_cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cidActionPerformed

    private void c_cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cnameActionPerformed

    private void c_cphoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cphoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cphoActionPerformed

    private void c_cperiadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cperiadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cperiadActionPerformed

    private void c_cemallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cemallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cemallActionPerformed

    private void com_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_editActionPerformed

    private void c_ctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ctypeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_c_ctypeActionPerformed

    private void com_selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_selectMouseClicked
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        if (c_cid.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(null, "wdh;kfha wxlh mqrjd ke;  ");
            this.setVisible(true);
        } else if (c_cname.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "wdh;kfha ku mqrjd ke;  ");
            this.setVisible(true);

        } else if (c_ctype.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "j¾.h mqrjd ke; ");
            this.setVisible(true);

        } else if (c_cperiad.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ld, iSudj mqrjd ke; ");
            this.setVisible(true);

        } else if (c_cpho.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh mqrjd ke; ");
            this.setVisible(true);

        } else if (c_cemall.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "B fï,a mqrjd ke; ");
            this.setVisible(true);

        } else if (c_caddress.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, ",smskh mqrjd ke; ");
            this.setVisible(true);

        } else {

            company_item s = company_item.getobj();
            String ty = c_ctype.getSelectedItem().toString();
            String cid = c_cid.getText();

            if (c_ctype.getSelectedItem().equals("ld¾hd,Sh Ndxv ")) {

                String sq = "SELECT cid as 'wxlh ',c_type as 'j¾.h ',item as 'Ndkavh ',price as 'uqo, ' FROM company_item WHERE cid LIKE '%" + cid + "%' AND c_type LIKE '%" + ty + "%'";

                try {
                    pst = con.prepareStatement(sq);
                    rs = pst.executeQuery();

                    s.item_table.setModel(DbUtils.resultSetToTableModel(rs));
                    s.setcolfront();
                } catch (Exception e) {
                }

            } else if (c_ctype.getSelectedItem().equals("bkaOk ")) {
                String sq = "SELECT cid as 'wxlh ',c_type as 'j¾.h ',item as 'Ndkavh ',price as 'uqo, ' FROM company_item WHERE cid LIKE '%" + cid + "%' AND c_type LIKE '%" + ty + "%'";

                try {
                    pst = con.prepareStatement(sq);
                    rs = pst.executeQuery();

                    s.item_table.setModel(DbUtils.resultSetToTableModel(rs));
                    s.setcolfront();

                } catch (Exception e) {
                }
            } else if (c_ctype.getSelectedItem().equals("fiajd Ndkav ")) {
                String sq = "SELECT cid as 'wxlh ',c_type as 'j¾.h ',item as 'Ndkavh ',price as 'uqo, ' FROM company_item WHERE cid LIKE '%" + cid + "%' AND c_type LIKE '%" + ty + "%'";

                try {
                    pst = con.prepareStatement(sq);
                    rs = pst.executeQuery();

                    s.item_table.setModel(DbUtils.resultSetToTableModel(rs));
                    s.setcolfront();

                } catch (Exception e) {
                }
            }

            JOptionPane.showMessageDialog(null, "id¾;lhs ");
            SLTB_sachin.Temp te = Temp.temp1;
            company_item com = company_item.getobj();
            com.setVisible(true);
            te.mainsetpanel.add(com, te.cmain);
            com_serch.getobj().setVisible(false);
            this.setVisible(false);
            com.setnew();
        }
    }//GEN-LAST:event_com_selectMouseClicked

    private void c_cidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_cidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cidMouseClicked

    private void c_cidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_cidKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            s.setText("wdh;k wxlh wl=rla úh fkdyel ");
        } else {

            s.setText("");
        }

    }//GEN-LAST:event_c_cidKeyPressed

    private void com_restMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_restMouseClicked
        // TODO add your handling code here:
        //mail=null;
        c_cpho.setText("");
        c_cperiad.setText("");
        c_cname.setText("");
        c_cid.setText("");
        c_cemall.setText("");
        c_caddress.setText("");
        c_ctype.setSelectedItem("ld¾hd,Sh Ndxv ");
    }//GEN-LAST:event_com_restMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
        // exit.setVisible(false);
    }//GEN-LAST:event_formPropertyChange

    private void com_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_addMouseClicked
        // TODO add your handling code here:
        String k = c_cid.getText();
        String p = c_cpho.getText();

        int z = k.length();
        int x = p.length();

        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        if (c_cid.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(null, "wdh;kfha wxlh mqrjd ke;  ");
            this.setVisible(true);
        } else if (z < 5) {
            JOptionPane.showMessageDialog(null, "ld¾hd, wxlh wxl 5lska iukaú; úh hq;=h ");
            this.setVisible(true);

        } else if (c_cname.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "wdh;kfha ku mqrjd ke;  ");
            this.setVisible(true);

        } else if (c_cperiad.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ld, iSudj mqrjd ke; ");
            this.setVisible(true);

        } else if (c_cpho.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh mqrjd ke; ");
            this.setVisible(true);

        } else if (x < 10) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh wxl 10la ;sìh hq;=h ");
            this.setVisible(true);

        } else if (c_cemall.getText().equalsIgnoreCase("")) {
            
            
            JOptionPane.showMessageDialog(null, "B fï,a mqrjd ke; ");
            this.setVisible(true);
            
           

        } else if (c_caddress.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, ",smskh mqrjd ke; ");
            this.setVisible(true);

        } else {
           
            String email = c_cemall.getText();
            try {
                InternetAddress emailAddr = new InternetAddress(email);
                emailAddr.validate();
            } catch (AddressException ex) {
                JOptionPane.showMessageDialog(this, "we;=,;a l, Bfï,a ,smskh jeros ", "ERROR: ", JOptionPane.ERROR_MESSAGE);
                setnew();
                return;
            }
            
            
            String tid = c_cid.getText();

            String ss = "SELECT * From supplier where cid=?";
            try {
                //System.out.println("sad");
                pst = con.prepareStatement(ss);
                pst.setInt(1, Integer.valueOf(tid));
                System.out.println(pst);
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ld¾hd, wxlh l,ska Ndú; lr we; ");
                    return;
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

            String cid = c_cid.getText();
            String cna = c_cname.getText();
            String typ = c_ctype.getSelectedItem().toString();
            int wa = Integer.valueOf(c_cperiad.getText());
            int pho = Integer.valueOf(c_cpho.getText());
            String emal = c_cemall.getText();
            String add = c_caddress.getText();

            String sd = "INSERT INTO supplier (cid,c_name,typeo,validate_year,phone_number,address,e_maill) values ('" + cid + "','" + cna + "','" + typ + "','" + wa + "','" + pho + "','" + add + "','" + emal + "')";

            try {
                pst = con.prepareStatement(sd);
                pst.execute();
                tablelord();
                setcolfront();
            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_com_addMouseClicked

    private void com_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_addActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_com_addActionPerformed

    private void c_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_tableMouseClicked
        // TODO add your handling code here:
        int r = c_table.getSelectedRow();

        String cid = c_table.getValueAt(r, 0).toString();
        String cna = c_table.getValueAt(r, 1).toString();
        String typ = c_table.getValueAt(r, 2).toString();
        String vali = c_table.getValueAt(r, 3).toString();
        String pho = c_table.getValueAt(r, 4).toString();
        String add = c_table.getValueAt(r, 5).toString();
        String emal = c_table.getValueAt(r, 6).toString();
        String vad = c_table.getValueAt(r, 7).toString();


        //set veriable
        //sss=cid;
        
        c_cid.setText(cid);
        c_cname.setText(cna);
        c_ctype.setSelectedItem(typ);
        c_cperiad.setText(vali);
        c_cpho.setText(pho);
        c_caddress.setText(add);
        c_cemall.setText(emal);
        mail=emal;


    }//GEN-LAST:event_c_tableMouseClicked

    private void com_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_editMouseClicked
        // TODO add your handling code here:
        String k = c_cid.getText();
        String p = c_cpho.getText();

        int z = k.length();
        int a = p.length();
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));
        
        if (c_cid.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(null, "wdh;kfha wxlh mqrjd ke;  ");
            this.setVisible(true);
        } else if (z < 5) {
            JOptionPane.showMessageDialog(null, "ld¾hd, wxlh wxl 5lska iukaú; úh hq;=h ");
            this.setVisible(true);

        } else if (c_cname.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "wdh;kfha ku mqrjd ke;  ");
            this.setVisible(true);

        } else if (c_cperiad.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ld, iSudj mqrjd ke; ");
            this.setVisible(true);

        } else if (c_cpho.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh mqrjd ke; ");
            this.setVisible(true);

        } else if (a < 10) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh wxl 10la ;sìh hq;=h ");
            this.setVisible(true);

        } else if (c_cemall.getText().equalsIgnoreCase("")) {
            
            
            JOptionPane.showMessageDialog(null, "B fï,a mqrjd ke; ");
            this.setVisible(true);
            
           

        } else if (c_caddress.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, ",smskh mqrjd ke; ");
            this.setVisible(true);

        }
        
        
        else{
            
             String email = c_cemall.getText();
            try {
                InternetAddress emailAddr = new InternetAddress(email);
                emailAddr.validate();
            } catch (AddressException ex) {
                JOptionPane.showMessageDialog(this, "we;=,;a l, Bfï,a ,smskh jeros ", "ERROR: ", JOptionPane.ERROR_MESSAGE);
                setnew();
                return;
            }
            
            
            
            
            
        int x = JOptionPane.showConfirmDialog(null, "kej; msrùug wjYHuo  ");
        if (x == 0) {
            String cid = c_cid.getText();
            String cna = c_cname.getText();
            String typ = c_ctype.getSelectedItem().toString();
            String vali = c_cperiad.getText();
            String pho = c_cpho.getText();
            String add = c_caddress.getText();
            String emal = c_cemall.getText();

            String sql = "UPDATE supplier  SET cid = '" + cid + "',c_name = '" + cna + "',typeo = '" + typ + "',validate_year = '" + vali + "',phone_number = '" + pho + "',address = '" + add + "',e_maill = '" + emal + "' WHERE cid = '" + cid + "'";
            //System.out.println(sql);

            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                
                tablelord();
                setcolfront();
            } catch (Exception e) {
            }

        }

        }
    }//GEN-LAST:event_com_editMouseClicked

    private void com_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_deleteMouseClicked
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));
        int y = JOptionPane.showConfirmDialog(null, "uld oeóug wjYHuo  ");

        if (y == 0) {
            String cid = c_cid.getText();

            String sql = "DELETE from  supplier  WHERE cid = '" + cid + "'";
            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                tablelord();
                setcolfront();
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_com_deleteMouseClicked

    private void com_selectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_selectMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_com_selectMouseEntered

    private void c_cidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_cidKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }

        String a = c_cid.getText();

        int i = a.length();
        if (i >= 5) {

            c_cid.setText(a.substring(0, i - 1));

        }
    }//GEN-LAST:event_c_cidKeyTyped

    private void c_cperiadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_cperiadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_c_cperiadKeyTyped

    private void c_cphoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_cphoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        String a = c_cpho.getText();

        int i = a.length();
        if (i >= 10) {

            c_cpho.setText(a.substring(0, i - 1));

        }
    }//GEN-LAST:event_c_cphoKeyTyped

    private void c_cperiadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_cperiadKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            show.setText("j,x.= ld,h wl=rla úh fkdyel ");
        } else {

            show.setText("");
        }

    }//GEN-LAST:event_c_cperiadKeyPressed

    private void c_cphoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_cphoKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            sh.setText("ÿrl;k wxlhg wl=re we;=,;a l, fkdyel ");
        } else {

            sh.setText("");
        }


    }//GEN-LAST:event_c_cphoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c_cpho.setText("0777139219");
        c_cperiad.setText("5");
        c_cname.setText("jika; lfâ ");
        c_cid.setText("50001");
        c_cemall.setText("kasunc969@gmail.com");
        c_caddress.setText("ud,fí mdr lvqfj, ");
        c_ctype.setSelectedItem("ldÂ¾hd,Sh Ndxv ");

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea c_caddress;
    private javax.swing.JTextField c_cemall;
    public javax.swing.JTextField c_cid;
    private javax.swing.JTextField c_cname;
    private javax.swing.JTextField c_cperiad;
    private javax.swing.JTextField c_cpho;
    public javax.swing.JComboBox<String> c_ctype;
    public javax.swing.JTable c_table;
    private javax.swing.JButton com_add;
    private javax.swing.JButton com_delete;
    private javax.swing.JButton com_edit;
    private javax.swing.JButton com_rest;
    private javax.swing.JButton com_select;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel s;
    private javax.swing.JLabel sh;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
