/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_supun_panal;

import SLTB_sachin.Class.EmailController;
import SLTB_sachin.Temp;
import com.ConnectionMysql.MysqlConnect;
import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author SUPUN
 */
public class Offce_item extends javax.swing.JPanel {

    private static Offce_item offce = null;
    public static JRViewer viewer = null;
    Connection con = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Offce_select1
     */
    private Offce_item() {

        initComponents();
        con = MysqlConnect.getDbCon();
    }

    public static Offce_item getobj() {
        if (offce == null) {
            offce = new Offce_item();
        }
        return offce;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tic_m_no = new javax.swing.JLabel();
        tic_m_no1 = new javax.swing.JLabel();
        tic_m_no2 = new javax.swing.JLabel();
        tic_m_no3 = new javax.swing.JLabel();
        tic_m_no4 = new javax.swing.JLabel();
        tic_m_no6 = new javax.swing.JLabel();
        tic_m_no7 = new javax.swing.JLabel();
        tic_m_no8 = new javax.swing.JLabel();
        o_item_status = new javax.swing.JComboBox<>();
        o_item_manufac = new javax.swing.JTextField();
        o_item_price = new javax.swing.JTextField();
        o_item_woranty = new javax.swing.JTextField();
        o_item_cid = new javax.swing.JTextField();
        o_item_no = new javax.swing.JTextField();
        o_item_qty = new javax.swing.JTextField();
        o_item_seno = new javax.swing.JTextField();
        se_sub = new javax.swing.JButton();
        se_reset = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        sh = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        tic_m_no.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no.setText("Ndkavfha ku ");

        tic_m_no1.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no1.setText(";;ajh ");

        tic_m_no2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no2.setText("uqo, ");

        tic_m_no3.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no3.setText("ksYamolh ");

        tic_m_no4.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no4.setText("m%udkh  ");

        tic_m_no6.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no6.setText("wdh;k wxlh ");

        tic_m_no7.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no7.setText("w¨;ajeähd lrkakf.a ÿrl;k wxlh ");

        tic_m_no8.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no8.setText("j.lSï ld,h ");

        o_item_status.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        o_item_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "w¨;a ", "Ndú;d lrk,o ", "m%;sixialrKh l, "}));

        o_item_manufac.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N

        o_item_price.setEditable(false);
        o_item_price.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        o_item_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o_item_priceKeyTyped(evt);
            }
        });

        o_item_woranty.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        o_item_woranty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                o_item_worantyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o_item_worantyKeyTyped(evt);
            }
        });

        o_item_cid.setEditable(false);
        o_item_cid.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        o_item_cid.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                o_item_cidPropertyChange(evt);
            }
        });
        o_item_cid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o_item_cidKeyTyped(evt);
            }
        });

        o_item_no.setEditable(false);
        o_item_no.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N

        o_item_qty.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        o_item_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                o_item_qtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o_item_qtyKeyTyped(evt);
            }
        });

        o_item_seno.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        o_item_seno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                o_item_senoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                o_item_senoKeyTyped(evt);
            }
        });

        se_sub.setBackground(new java.awt.Color(239, 219, 88));
        se_sub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eadd.png"))); // NOI18N
        se_sub.setText("Submit");
        se_sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                se_subMouseClicked(evt);
            }
        });
        se_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                se_subActionPerformed(evt);
            }
        });

        se_reset.setBackground(new java.awt.Color(255, 153, 153));
        se_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arefresh.png"))); // NOI18N
        se_reset.setText("Reset");
        se_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                se_resetMouseClicked(evt);
            }
        });
        se_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                se_resetActionPerformed(evt);
            }
        });

        show.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(204, 0, 0));

        sh.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        sh.setForeground(new java.awt.Color(204, 0, 0));

        s.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        s.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setText("Demo");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tic_m_no7, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(se_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tic_m_no2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tic_m_no3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tic_m_no8, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tic_m_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tic_m_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tic_m_no4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tic_m_no6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addComponent(o_item_manufac)
                        .addComponent(o_item_price)
                        .addComponent(o_item_qty)
                        .addComponent(o_item_cid, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addComponent(o_item_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(o_item_woranty, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addComponent(o_item_seno)
                        .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(o_item_no, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addComponent(sh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(se_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o_item_no, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tic_m_no, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o_item_cid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tic_m_no6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tic_m_no4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_item_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tic_m_no2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_item_price, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tic_m_no3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_item_manufac, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o_item_woranty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tic_m_no8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tic_m_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_item_status, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o_item_seno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tic_m_no7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(se_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(se_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void se_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_se_subActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_se_subActionPerformed

    private void se_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_se_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_se_resetActionPerformed

    private void se_subMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se_subMouseClicked
        // TODO add your handling code here:
        String o = o_item_seno.getText();
        int w = o.length();

        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));
        if (o_item_no.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ndkavfha ku we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (o_item_cid.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "wdh;kfha wxlh mqrjd ke;  ");
            this.setVisible(true);

        } else if (o_item_qty.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "m%udkh we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (o_item_price.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "uqo, we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (o_item_manufac.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ksYamolhd we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (o_item_woranty.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "j.lSï ld,h we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (o_item_status.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, ";;ajh f;dard ke; ");
            this.setVisible(true);

        } else if (o_item_seno.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (w < 10 && 10 < w) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh wxl 10la ;sìh hq;=h ");
            this.setVisible(true);

        } else {
            String cid = o_item_cid.getText();
            String nam = o_item_no.getText();
            int qty = Integer.valueOf(o_item_qty.getText());
            double pric = Double.valueOf(o_item_price.getText());
            String manu = o_item_manufac.getText();
            int wora = Integer.valueOf(o_item_woranty.getText());
            String stat = o_item_status.getSelectedItem().toString();
            int pno = Integer.valueOf(o_item_seno.getText());

            String q = "INSERT INTO sup_offce (cid,item_name,qty,price,manufac,woranty,status,se_co_no) values ('" + cid + "','" + nam + "','" + qty + "','" + pric + "','" + manu + "','" + wora + "','" + stat + "','" + pno + "')";
            try {
                pst = con.prepareStatement(q);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(tender.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            double pr = qty * pric;
            
            String k = "INSERT INTO all_de (cid,iname,qty,price,manu,woran,stat) values ('" + cid + "','" + nam + "','" + qty + "','" + pr + "','" + manu + "','" + wora + "','" + stat + "')";
            try {
                pst = con.prepareStatement(k);
                pst.execute();
            } catch (SQLException ex) {
                
            }

            JOptionPane.showMessageDialog(null, "id¾;lhs ");

            SLTB_sachin.Temp te = SLTB_sachin.Temp.temp1;

            Connection conn = com.ConnectionMysql.MysqlConnect.getDbCon();
            Map par = new HashMap();
            par.put(null, null);

            this.viewer = null;
            String fpath = null;
            String fname = null;
            try {

                fname = "re.pdf";
                fpath = "C:/Users/Public/" + fname;
                JasperPrint print = JasperFillManager.fillReport("src\\SLTB_supun_report\\officereport.jasper", par, conn);
                JasperExportManager.exportReportToPdfFile(print, fpath);
            } catch (Exception e) {
                e.printStackTrace();
            }
            String sub = "subject";
            String masage = "  gjhfjgjkgkkg ";
            EmailController em = new EmailController();
            String to[] = new String[1];
            to[0] = chooce_comp.mail;
            em.sentemail(to, sub, masage, fpath, fname);

            JLabel label = new JLabel("Bfï,a mksúvh heùu id¾;hs ");
            label.setFont(new Font("FMBindumathi", Font.BOLD, 18));
            JOptionPane.showMessageDialog(this, label, "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_se_subMouseClicked

    private void se_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se_resetMouseClicked
        // TODO add your handling code here:
        //o_item_cid.setText("");
        o_item_manufac.setText("");
        //o_item_no.setText("");
        o_item_seno.setText("");
        o_item_woranty.setText("");
        o_item_status.setSelectedItem("w¨;a ");
        //o_item_price.setText("");
        o_item_qty.setText("");

    }//GEN-LAST:event_se_resetMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
        //offi_exit.setVisible(false);
    }//GEN-LAST:event_formPropertyChange

    private void o_item_cidPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_o_item_cidPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_o_item_cidPropertyChange

    private void o_item_cidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_cidKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_o_item_cidKeyTyped

    private void o_item_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_qtyKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_o_item_qtyKeyTyped

    private void o_item_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_priceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_o_item_priceKeyTyped

    private void o_item_worantyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_worantyKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        String a = o_item_woranty.getText();

        int i = a.length();
        if (i >= 1) {

            o_item_woranty.setText(a.substring(0, i-1));

        }

    }//GEN-LAST:event_o_item_worantyKeyTyped

    private void o_item_senoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_senoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        String a = o_item_seno.getText();

        int i = a.length();
        if (i >= 10) {

            o_item_seno.setText(a.substring(0, i - 1));

        }
    }//GEN-LAST:event_o_item_senoKeyTyped

    private void o_item_senoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_senoKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            show.setText("ÿrl;k wxlhg wl=re we;=,;a l, fkdyel ");
        } else {

            show.setText("");
        }


    }//GEN-LAST:event_o_item_senoKeyPressed

    private void o_item_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_qtyKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            sh.setText("Ndkav m%udkhg wl=re we;=,;a l, fkdyel ");
        } else {

            sh.setText("");
        }
    }//GEN-LAST:event_o_item_qtyKeyPressed

    private void o_item_worantyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_o_item_worantyKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            s.setText("j.lSï ld,hg wl=re we;=,;a l, fkdyel ");
        } else {

            s.setText("");
        }
    }//GEN-LAST:event_o_item_worantyKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        o_item_manufac.setText("oïfrda ");
        
        	o_item_seno.setText("0775211812");
       	 o_item_woranty.setText("2");
        	o_item_status.setSelectedItem("w¨;a ");
        
        	o_item_qty.setText("12");

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JTextField o_item_cid;
    private javax.swing.JTextField o_item_manufac;
    public javax.swing.JTextField o_item_no;
    public javax.swing.JTextField o_item_price;
    private javax.swing.JTextField o_item_qty;
    private javax.swing.JTextField o_item_seno;
    private javax.swing.JComboBox<String> o_item_status;
    private javax.swing.JTextField o_item_woranty;
    private javax.swing.JLabel s;
    private javax.swing.JButton se_reset;
    private javax.swing.JButton se_sub;
    private javax.swing.JLabel sh;
    private javax.swing.JLabel show;
    private javax.swing.JLabel tic_m_no;
    private javax.swing.JLabel tic_m_no1;
    private javax.swing.JLabel tic_m_no2;
    private javax.swing.JLabel tic_m_no3;
    private javax.swing.JLabel tic_m_no4;
    private javax.swing.JLabel tic_m_no6;
    private javax.swing.JLabel tic_m_no7;
    private javax.swing.JLabel tic_m_no8;
    // End of variables declaration//GEN-END:variables
}
