/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_supun_panal;

import SLTB_sachin.Class.EmailController;
import SLTB_sachin.Temp;
import com.ConnectionMysql.MysqlConnect;
import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author SUPUN
 */
public class tikcet_maching extends javax.swing.JPanel {

    private static tikcet_maching timachi = null;
    public static JRViewer viewer = null;
    Connection con = null;
    PreparedStatement pst = null;

    /**
     * Creates new form tikcet_maching
     */
    private tikcet_maching() {

        initComponents();
        con = MysqlConnect.getDbCon();
    }

    public static tikcet_maching getobj() {
        if (timachi == null) {
            timachi = new tikcet_maching();
        }
        return timachi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ti_manufac = new javax.swing.JLabel();
        ti_price = new javax.swing.JLabel();
        ti_se_no = new javax.swing.JLabel();
        ti_status = new javax.swing.JLabel();
        ti_barand = new javax.swing.JLabel();
        ti_woranty = new javax.swing.JLabel();
        ticet_barnd = new javax.swing.JTextField();
        ticet_se_no = new javax.swing.JTextField();
        ticet_waranty = new javax.swing.JTextField();
        ticet_price = new javax.swing.JTextField();
        ticet_manufac = new javax.swing.JTextField();
        se_reset = new javax.swing.JButton();
        se_sub = new javax.swing.JButton();
        ticet_status = new javax.swing.JComboBox<>();
        tic_m_no1 = new javax.swing.JLabel();
        ticet_cid = new javax.swing.JTextField();
        show = new javax.swing.JLabel();
        sh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        ti_manufac.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        ti_manufac.setText("ksYamdolhd ");

        ti_price.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        ti_price.setText("ñ, ");

        ti_se_no.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        ti_se_no.setText("w¨;ajeähd lrkakf. ÿrl;k wxlh ");

        ti_status.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        ti_status.setText(";a;ajh ");

        ti_barand.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        ti_barand.setText("udos,sh ");

        ti_woranty.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        ti_woranty.setText("j.lSï ld,h ");

        ticet_se_no.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        ticet_se_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ticet_se_noKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ticet_se_noKeyTyped(evt);
            }
        });

        ticet_waranty.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        ticet_waranty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ticet_warantyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ticet_warantyKeyTyped(evt);
            }
        });

        ticet_price.setEditable(false);
        ticet_price.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ticet_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ticet_priceKeyTyped(evt);
            }
        });

        ticet_manufac.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N

        se_reset.setBackground(new java.awt.Color(255, 153, 153));
        se_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arefresh.png"))); // NOI18N
        se_reset.setText("Reset");
        se_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                se_resetMouseClicked(evt);
            }
        });
        se_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                se_resetActionPerformed(evt);
            }
        });

        se_sub.setBackground(new java.awt.Color(239, 219, 88));
        se_sub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ecorre.png"))); // NOI18N
        se_sub.setText("Submit");
        se_sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                se_subMouseClicked(evt);
            }
        });
        se_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                se_subActionPerformed(evt);
            }
        });

        ticet_status.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        ticet_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "w¨;a ", "Ndú;d lrk,o ", "m%;sixialrKh l, "}));

        tic_m_no1.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        tic_m_no1.setText("wdh;k wxlh ");

        ticet_cid.setEditable(false);
        ticet_cid.setFont(new java.awt.Font("FMBindumathi", 0, 18)); // NOI18N
        ticet_cid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ticet_cidKeyTyped(evt);
            }
        });

        show.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 0, 0));

        sh.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        sh.setForeground(new java.awt.Color(204, 0, 0));

        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(se_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tic_m_no1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ti_status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ti_se_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ti_manufac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ti_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ti_woranty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ti_barand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(se_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ticet_se_no, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ticet_manufac, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ticet_price, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ticet_status, javax.swing.GroupLayout.Alignment.LEADING, 0, 508, Short.MAX_VALUE)
                                    .addComponent(ticet_waranty, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ticet_cid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticet_barnd, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticet_cid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tic_m_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ti_barand, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticet_barnd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticet_waranty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ti_woranty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticet_price, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ti_price, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticet_manufac, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ti_manufac, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticet_se_no, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ti_se_no, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticet_status, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ti_status, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(se_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(se_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void se_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_se_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_se_resetActionPerformed

    private void se_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_se_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_se_subActionPerformed

    private void se_subMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se_subMouseClicked
        // TODO add your handling code here:
        String a = ticet_se_no.getText();
        int q = a.length();
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        if (ticet_cid.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "wdh;kfha wxlh mqrjd ke;  ");
            this.setVisible(true);

        } else if (ticet_barnd.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "j¾.h we;=,;a lr ke; ");
            this.setVisible(true);
        } else if (ticet_waranty.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "j.lSï ld,h we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (ticet_price.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "uqo, we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (ticet_manufac.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "ksYamolhd we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (ticet_se_no.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh we;=,;a lr ke; ");
            this.setVisible(true);

        } else if (q < 10) {
            JOptionPane.showMessageDialog(null, "ÿrl;k wxlh wxl 10la ;sìh hq;=h ");
            this.setVisible(true);

        } else if (ticet_status.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, ";;ajh f;dard ke; ");
            this.setVisible(true);

        } else {
            
            company_item c = company_item.getobj();
            
            int r = c.item_table.getSelectedRow();
            
            String cid = ticet_cid.getText();
            String ks = c.item_table.getValueAt(r, 2).toString();
            String br = ticet_barnd.getText();
            String wor = ticet_waranty.getText();
            String pr = ticet_price.getText();
            String manu = ticet_manufac.getText();
            String scn = ticet_se_no.getText();
            String sta = ticet_status.getSelectedItem().toString();

            String ti = "INSERT INTO ticketmachine (Cid,M_Warranty_Period,M_Brand,M_Price,M_Manufacturer,M_ScontactNo,M_Status) values ('" + cid + "','" + wor + "','" + br + "','" + pr + "','" + manu + "','" + scn + "','" + sta + "')";

            try {
                pst = con.prepareStatement(ti);
                pst.execute();
            } catch (Exception e) {
            }
            
            
            
            
            String k = "INSERT INTO all_de (cid,iname,price,manu,woran,stat,se_con) values ('" + cid + "','" + ks + "','" + pr + "','" + manu + "','" + wor + "','" + sta + "','" + scn + "')";
            try {
                pst = con.prepareStatement(k);
                pst.execute();
            } catch (SQLException ex) {
                
            }

            JOptionPane.showMessageDialog(null, "id¾;lhs ");
            
            Connection conn = com.ConnectionMysql.MysqlConnect.getDbCon();
            Map par = new HashMap();
            par.put(null, null);

            this.viewer = null;
            String fpath = null;
            String fname = null;
            try {

                fname = "re.pdf";
                fpath = "C:/Users/Public/" + fname;
                JasperPrint print = JasperFillManager.fillReport("src\\SLTB_supun_report\\ticatmachinrep.jasper", par, conn);
                JasperExportManager.exportReportToPdfFile(print, fpath);
            } catch (Exception e) {
                e.printStackTrace();
            }
            String sub = "subject";
            String masage = "  gjhfjgjkgkkg ";
            EmailController em = new EmailController();
            String to[] = new String[1];
            to[0] = chooce_comp.mail;
            em.sentemail(to, sub, masage, fpath, fname);

            JLabel label = new JLabel("Bfï,a mksúvh heùu id¾;hs ");
            label.setFont(new Font("FMBindumathi", Font.BOLD, 18));
            JOptionPane.showMessageDialog(this, label, "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_se_subMouseClicked

    private void se_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se_resetMouseClicked
        // TODO add your handling code here:
       // ticet_cid.setText("");
        ticet_barnd.setText("");

        ticet_manufac.setText("");

        //ticet_price.setText("");

        ticet_se_no.setText("");
        ticet_status.setSelectedItem("w¨;a ");
        ticet_waranty.setText("");


    }//GEN-LAST:event_se_resetMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
        // tic_exit.setVisible(false);
    }//GEN-LAST:event_formPropertyChange

    private void ticet_cidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticet_cidKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        String a = ticet_cid.getText();

        int i = a.length();
        if (i >= 5) {

            ticet_cid.setText(a.substring(0, i - 1));

        }
    }//GEN-LAST:event_ticet_cidKeyTyped

    private void ticet_warantyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticet_warantyKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        String a = ticet_waranty.getText();

        int i = a.length();
        if (i >= 1) {

            ticet_waranty.setText(a.substring(0, i-1));

        }
    }//GEN-LAST:event_ticet_warantyKeyTyped

    private void ticet_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticet_priceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_ticet_priceKeyTyped

    private void ticet_se_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticet_se_noKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        String a = ticet_se_no.getText();

        int i = a.length();
        if (i >= 10) {

            ticet_se_no.setText(a.substring(0, i - 1));

        }
    }//GEN-LAST:event_ticet_se_noKeyTyped

    private void ticet_warantyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticet_warantyKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            show.setText("j.lSï ld,hg we;=,;a l, fkdyel ");
        } else {

            show.setText("");
        }
    }//GEN-LAST:event_ticet_warantyKeyPressed

    private void ticet_se_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticet_se_noKeyPressed
        // TODO add your handling code here:
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("FMBindumathi", Font.BOLD, 25)));

        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {

            sh.setText("ÿrl;k wxlhg wl=re we;=,;a l, fkdyel ");
        } else {

            sh.setText("");
        }
    }//GEN-LAST:event_ticet_se_noKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                ticet_barnd.setText("samsung");
        ticet_manufac.setText("ieïiqka.a ");
        ticet_se_no.setText("0777854535");
        ticet_status.setSelectedItem("w¨;a ");
        ticet_waranty.setText("5");

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton se_reset;
    private javax.swing.JButton se_sub;
    private javax.swing.JLabel sh;
    private javax.swing.JLabel show;
    private javax.swing.JLabel ti_barand;
    private javax.swing.JLabel ti_manufac;
    private javax.swing.JLabel ti_price;
    private javax.swing.JLabel ti_se_no;
    private javax.swing.JLabel ti_status;
    private javax.swing.JLabel ti_woranty;
    private javax.swing.JLabel tic_m_no1;
    private javax.swing.JTextField ticet_barnd;
    public javax.swing.JTextField ticet_cid;
    private javax.swing.JTextField ticet_manufac;
    public javax.swing.JTextField ticet_price;
    private javax.swing.JTextField ticet_se_no;
    private javax.swing.JComboBox<String> ticet_status;
    private javax.swing.JTextField ticet_waranty;
    // End of variables declaration//GEN-END:variables
}
