/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_sandu.fuel;

import static SLTB_Bimsara.Route.RouteIdSide.viewer;
import com.ConnectionMysql.MysqlConnect;
import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author sanduu
 */
public class stock extends javax.swing.JPanel {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public static JRViewer viewer = null;
    private static stock stock1 = null;

    public stock() {

        initComponents();
        jTable1.getTableHeader().setFont(new Font("FMBindumathi", Font.BOLD, 14));

        con = MysqlConnect.getDbCon();
        tableLoad();
    }

    public void setcolfront() {
        DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
            Font font = new Font("Calibri", Font.BOLD, 14);

            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus,
                    int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus,
                        row, column);
                setFont(font);
                return this;
            }

        };
        jTable1.getColumnModel().getColumn(2).setCellRenderer(r);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(r);

    }

    public static stock getobj() {
        if (stock1 == null) {
            stock1 = new stock();
        }
        return stock1;
    }

    public void tableLoad() {

        try {
            String sql = "Select FuelId, Name, Liters, S_Date from fuelstock";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            setcolfront();
            jTable1.getColumnModel().getColumn(0).setHeaderValue("j¾. wxlh");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("bkaOk j¾.h");
            jTable1.getColumnModel().getColumn(2).setHeaderValue(",Sg¾ .Kk");
            jTable1.getColumnModel().getColumn(3).setHeaderValue(".nvd oskh ");
        } catch (Exception e) {
        }
    }

   private void clear() {
        
        ty.setText(null);
        lit.setText(null);
        jLabel3.setText(null);
        jLabel3.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lit = new javax.swing.JTextField();
        ty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sr = new javax.swing.JButton();
        srch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        report = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1149, 710));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("FMBindumathi", 1, 36)); // NOI18N
        jLabel1.setText("      bkaOk .nvdj ");

        jLabel4.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel4.setText(",Sg¾ .Kk ");

        jLabel6.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel6.setText("bkaOk j¾.h ");

        jTable1.setFont(new java.awt.Font("FMBindumathi", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "j¾. wxlh ", "bkaOk j¾.h ", ",Sg¾ .Kk ", ".nvd oskh "
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                litActionPerformed(evt);
            }
        });
        lit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                litKeyTyped(evt);
            }
        });

        ty.setFont(new java.awt.Font("FMBindumathi", 0, 11)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eupdate.png"))); // NOI18N
        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edelete.png"))); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eadd.png"))); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        jLabel2.setText("bkaOk wxlh ");

        sr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/esearch.png"))); // NOI18N
        sr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                srMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                srMouseReleased(evt);
            }
        });
        sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srActionPerformed(evt);
            }
        });
        sr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srKeyReleased(evt);
            }
        });

        srch.setFont(new java.awt.Font("FMBindumathi", 0, 10)); // NOI18N
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        srch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        jLabel5.setText("bkaOk j¾.h ");

        report.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/request-report.png"))); // NOI18N
        report.setText("Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        jButton4.setText("Demo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ty, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sr, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel5)
                .addGap(104, 104, 104)
                .addComponent(srch, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(report)
                        .addGap(119, 119, 119)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(srch))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(report))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String type = ty.getText();
        String liter = lit.getText();
        //System.out.println("lk");
        if (type.equals("") || liter.equals("")) {
            JLabel label = new JLabel("ish¨ o;a; we;=,;a lrkak ");
            label.setFont(new Font("FMBindumathi", Font.BOLD, 15));
            JOptionPane.showMessageDialog(stock.getobj(), label, "infoBox=", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                //double p = Double.parseDouble(liter);
                String s = "select * from fuelstock where Name=?";

                pst = con.prepareStatement(s);
                pst.setString(1, type);
                //System.out.println(pst);
                rs = pst.executeQuery();
                //System.out.println(";l");
                if (rs.next()) {

                    JLabel label = new JLabel("oekg mj;sk o;a;hls  ");
                    label.setFont(new Font("FMBindumathi", Font.BOLD, 15));
                    JOptionPane.showMessageDialog(stock.getobj(), label, "infoBox=", JOptionPane.INFORMATION_MESSAGE);

                    return;

                } else {
                    String sq = "INSERT INTO fuelstock (Name,Liters)values ('" + type + "','" + liter + "')";
                    pst = con.prepareStatement(sq);
                    //System.out.println(pst);
                    //System.out.println(pst);
                    pst.executeUpdate(sq);
                    //load table
                    tableLoad();
                    JOptionPane.showMessageDialog(null, "sucsesfullu entered");
                    clear();
                }

            } catch (Exception e) {
                e.printStackTrace();
//                JLabel label1 = new JLabel("ixLHd muKla we;=,;a lrkak ");
//                label1.setFont(new Font("FMBindumathi", Font.BOLD, 15));
//                JOptionPane.showMessageDialog(stock.getobj(), label1, "infoBox=", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do You Want To Delete This?");
        if (x == 0) {
            String fuelId = jLabel3.getText();
            String sq = "DELETE FROM fuelstock where FuelID='" + fuelId + "'";

            try {
                pst = con.prepareStatement(sq);
                pst.execute();
                //load table
                tableLoad();
                clear();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you expect to edit?");
        if (x == 0) {
            String type = ty.getText();
            String liter = lit.getText();
            String fuelId = jLabel3.getText();
            String sq = "UPDATE fuelstock SET Name='" + type + "' ,Liters= '" + liter + "' where fuelID='" + fuelId + "' ";

            try {
                //double p = Double.parseDouble(liter);
                String s = "select * from fuelstock where Name=?";

                pst = con.prepareStatement(s);
                pst.setString(1, type);
                //System.out.println(pst);
                rs = pst.executeQuery();
                //System.out.println(";l");
                if (rs.next()) {

                    JLabel label = new JLabel("oekg mj;sk o;a;hls  ");
                    label.setFont(new Font("FMBindumathi", Font.BOLD, 15));
                    JOptionPane.showMessageDialog(stock.getobj(), label, "infoBox=", JOptionPane.INFORMATION_MESSAGE);

                    return;

                } else {
                    pst = con.prepareStatement(sq);
                    pst.execute();

                    //load table
                    tableLoad();
                }
                clear();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        String typeNo = jTable1.getValueAt(row, 0).toString();
        String type = jTable1.getValueAt(row, 1).toString();
        String liter = jTable1.getValueAt(row, 2).toString();
        String Sdate = jTable1.getValueAt(row, 3).toString();

        ty.setText(type);
        lit.setText(liter);
        jLabel3.setText(typeNo);
    }//GEN-LAST:event_jTable1MouseClicked

    private void srMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srMouseReleased
//        String type = srch.getText();
//
//        String sq = "SELECT FuelID,Name,Liters,S_Date FROM fuelstock where Name LIKE '%" + type + "%'";
//
//        try {
//            pst = con.prepareStatement(sq);
//            rs = pst.executeQuery();
//            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//            setcolfront();
//            jTable1.getColumnModel().getColumn(0).setHeaderValue("j¾. wxlh");
//            jTable1.getColumnModel().getColumn(1).setHeaderValue("bkaOk j¾.h");
//            jTable1.getColumnModel().getColumn(2).setHeaderValue(",Sg¾ .Kk");
//            jTable1.getColumnModel().getColumn(3).setHeaderValue(".nvd oskh ");
//
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_srMouseReleased

    private void srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srActionPerformed
//        String type = srch.getText();
//
//        String sq = "SELECT FuelID,Name,Liters,S_Date FROM fuelstock where Name LIKE '%" + type + "%'";
//        
//        try {
//            pst = con.prepareStatement(sq);
//            rs = pst.executeQuery();
//            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_srActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srchActionPerformed

    private void srMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srMouseEntered
//         String type = srch.getText();
//
//        String sq = "SELECT FuelID,Name,Liters,S_Date FROM fuelstock where Name LIKE '%" + type + "%'";
//        
//        try {
//            pst = con.prepareStatement(sq);
//            rs = pst.executeQuery();
//            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_srMouseEntered

    private void litActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_litActionPerformed
        // TODO add your handling code here:
        // jLabel4.setText(lit.getText());
    }//GEN-LAST:event_litActionPerformed

    private void litKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_litKeyTyped
        char v = evt.getKeyChar();
        if (!(Character.isDigit(v))
                || (v == KeyEvent.VK_BACKSPACE) || (v == KeyEvent.VK_DELETE)) {
            {
//             JLabel label1 = new JLabel("ixLHd muKla we;=,;a lrkak ");
//                label1.setFont(new Font("FMBindumathi", Font.BOLD, 15));
//                JOptionPane.showMessageDialog(stock.getobj(), label1, "infoBox=", JOptionPane.INFORMATION_MESSAGE);
                evt.consume();
            }

    }//GEN-LAST:event_litKeyTyped
    }

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed

        stock stoc = stock.getobj();
        

        if (report.getText().equalsIgnoreCase("Report")) {
            report.setBackground(new java.awt.Color(255, 51, 51));
            report.setText("Cancel");

            stoc.setVisible(false);
           
            report("src\\SLTB_sandu\\reports\\stock.jasper");

        } else if (report.getText().equalsIgnoreCase("Cancel")) {
            report.setBackground(new java.awt.Color(102, 153, 255));
            report.setText("Report");
            stoc.setVisible(true);
            viewer.setVisible(false);
            

        }


    }//GEN-LAST:event_reportActionPerformed

    private void srKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srKeyReleased

    private void srchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchKeyReleased
       String type = srch.getText();

        String sq = "SELECT FuelID,Name,Liters,S_Date FROM fuelstock where Name LIKE '%" + type + "%'";

        try {
            pst = con.prepareStatement(sq);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            setcolfront();
            jTable1.getColumnModel().getColumn(0).setHeaderValue("j¾. wxlh");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("bkaOk j¾.h");
            jTable1.getColumnModel().getColumn(2).setHeaderValue(",Sg¾ .Kk");
            jTable1.getColumnModel().getColumn(3).setHeaderValue(".nvd oskh ");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_srchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ty.setText("ãi,a2");
        lit.setText("500");
    }//GEN-LAST:event_jButton4ActionPerformed
    public void report(String reportPath) {

        Connection conn = com.ConnectionMysql.MysqlConnect.getDbCon();
        SLTB_sachin.Temp te = SLTB_sachin.Temp.temp1;
        Map par = new HashMap();
        par.put("le", 500.0);

        viewer = null;

        //Generating reports inside jpanel
        try {

            JasperPrint print = JasperFillManager.fillReport(reportPath, par, conn);
            viewer = new JRViewer(print);
            viewer.setOpaque(true);
            viewer.setVisible(true);
            viewer.setPreferredSize(new Dimension(1149, 710));
        } catch (Exception e) {
            e.printStackTrace();
        }

        te.mainsetpanel.add(viewer, te.cmain);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lit;
    private javax.swing.JButton report;
    private javax.swing.JButton sr;
    private javax.swing.JTextField srch;
    private javax.swing.JTextField ty;
    // End of variables declaration//GEN-END:variables
}
