/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SLTB_isuru.finance;
import SLTB_sachin.Temp;

import SLTB_isuru.Class.Finance;
import java.util.HashMap;

/**
 *
 * @author Chamika Prabath
 */
public class RouteReportSide extends javax.swing.JPanel {
private static RouteReportSide SalariesSide=null;

    /**
     * Creates new form ManageEmployeeSide
     */
    public RouteReportSide() {
        initComponents();
    }
 public static RouteReportSide getobj(){
        if(SalariesSide==null){
            SalariesSide=new RouteReportSide();
        }
        return SalariesSide;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        report = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(220, 280));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(220, 280));

        report.setBackground(new java.awt.Color(0, 153, 153));
        report.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/request-report.png"))); // NOI18N
        report.setText("Report");
        report.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(report)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        Finance f1=new Finance();
        RouteReport RR=RouteReport.getobj();
        RouteReportUp RRup=RouteReportUp.getobj();
        String se=RRup.search.getText();
      
        String rPath="src\\SLTB_isuru\\report\\RouteReport1.jasper";
                     
                HashMap par = new HashMap();
                            
                            par.put("tid", se);
                     
                            if(report.getText().equalsIgnoreCase("Report")){
                                report.setBackground(new java.awt.Color(255, 51, 51));
                                report.setText("Cancel");
                                
                                RRup.setVisible(false);
                                RR.setVisible(false);
                                //report.setVisible(false);
                                f1.ParameterizedReport(rPath,par);
                                

                            }
                            else if(report.getText().equalsIgnoreCase("Cancel")){
                                report.setBackground(new java.awt.Color(102, 153, 255));
                                report.setText("Report");

                                f1.viewer.setVisible(false);
                                RRup.setVisible(true);
                                RR.setVisible(true);
                                //dailyReport.setVisible(true);
                             }
    }//GEN-LAST:event_reportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton report;
    // End of variables declaration//GEN-END:variables
}
