/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_chamika.employee;

import SLTB_sachin.Temp;
import SLTB_chamika.Class.Employee;
import com.ConnectionMysql.MysqlConnect;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Chamika Prabath
 */
public class ManageEmployeeSide extends javax.swing.JPanel {
private static ManageEmployeeSide manageEside=null;

    /**
     * Creates new form ManageEmployeeSide
     */
    public ManageEmployeeSide() {
        initComponents();
    }
 public static ManageEmployeeSide getobj(){
        if(manageEside==null){
            manageEside=new ManageEmployeeSide();
        }
        return manageEside;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        report = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(220, 280));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(220, 280));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ePrint.png"))); // NOI18N
        jButton1.setText("Print ID Card");
        jButton1.setToolTipText("Print ID Card");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        report.setBackground(new java.awt.Color(0, 153, 153));
        report.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/request-report.png"))); // NOI18N
        report.setText("Report");
        report.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(report)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:      
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ManageEmployee manageE=ManageEmployee.getobj();
        ManageEmployeeUp manageEup=ManageEmployeeUp.getobj();
        ManageEmployeeSide manageEside=ManageEmployeeSide.getobj();
        EmployeeID empid =EmployeeID.getobj();
              
        manageE.setVisible(false);
        manageEup.setVisible(false);
        manageEside.setVisible(false);
        empid.setVisible(true);
                
        Temp tmp=Temp.temp1;
        tmp.mainsetpanel.add(manageE,tmp.cmain);
        tmp.upsetpanel.add(manageEup,tmp.cup);
        tmp.sidesetpanel.add(manageEside,tmp.cside);
        tmp.mainsetpanel.add(empid,tmp.cmain);
        
         /**
        * Assign values to employee id labels 
        */
        String Name=manageE.name.getText();
        empid.name.setText(Name);
        String Nic=manageE.nic.getText();
        empid.nic.setText(Nic);
        String gra=(String) manageE.grade.getSelectedItem();
        empid.grade.setText(gra);
        
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        Calendar c=Calendar.getInstance();
        c.setTime(new Date());
        String date1=sdf.format(c.getTime());
        empid.day.setText(date1);
        
        try {	/*calling the mysql connection class*/
            Connection conn=MysqlConnect.getDbCon();
         String query="select SalaryNo from Employee where E_NIC='"+Nic+"'";
            Statement stmt= conn.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
            int i=rs.getInt("SalaryNo");
            
         String sal=Integer.toString(i);
         empid.salaryno.setText(sal);
            }
        } catch (Exception e) {
            System.err.println(e);
        }
        
        
        
               try {
            BufferedImage bufImg=ImageIO.read(new File("d:\\QR.png"));
            empid.qrpic.setIcon(new ImageIcon(bufImg));

            }
            catch (IOException ex) {
                System.out.println("Unable to read QR image file");
            }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        Employee e1=new Employee();
        ManageEmployee manageE=ManageEmployee.getobj();
        ManageEmployeeUp manageEup=ManageEmployeeUp.getobj();
      
        if(report.getText().equalsIgnoreCase("Report")){
            report.setBackground(new java.awt.Color(255, 51, 51));
            report.setText("Cancel");
            
            manageEup.setVisible(false);
            manageE.setVisible(false);
            e1.report("src\\SLTB_chamika\\report\\EmployeeReport.jasper");
            
        }
        else if(report.getText().equalsIgnoreCase("Cancel")){
            report.setBackground(new java.awt.Color(102, 153, 255));
            report.setText("Report");
            manageEup.setVisible(true);
            e1.viewer.setVisible(false);
            manageE.setVisible(true);
           
        }
    }//GEN-LAST:event_reportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton report;
    // End of variables declaration//GEN-END:variables
}
