/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_chamika.employee;

import com.ConnectionMysql.MysqlConnect;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamika Prabath
 */
public class ManageAttendance extends javax.swing.JPanel {
private static ManageAttendance manageA=null;
    /**
     * Creates new form ManageAttendence
     */
    public ManageAttendance() {
        initComponents();
           
    }
public static ManageAttendance getobj(){
        if(manageA==null){
            manageA=new ManageAttendance();
        }
        return manageA;
    }

 public void TableLoad1(){
          try{
    Atab1.getTableHeader().setFont(new Font("FMBindumathi", Font.BOLD, 18));
    setcolfront();
   
            String att="1";
            
             Connection conn=MysqlConnect.getDbCon();
              Date date = new Date();
            String date1= new SimpleDateFormat("yyyy-MM-dd").format(date);
            
            String query="select SalaryNo,Grade,Availability from OfficerAttendance where Attendance='"+att+"' and A_Date LIKE '%"+date1+"%'" ;
                    Statement stmt= conn.createStatement();
                    ResultSet rs=stmt.executeQuery(query);
                    Atab1.setModel(DbUtils.resultSetToTableModel(rs));
                    
Atab1.getColumn("SalaryNo").setHeaderValue("fõ;k wxlh ");
Atab1.getColumn("Grade").setHeaderValue("fY%aKsh ");
Atab1.getColumn("Availability").setHeaderValue("ld¾hfha kshq;= ");
Atab1.repaint();

                  
        }catch(Exception e){
            
        }
 }
 public void TableLoad2(){
          try{
             Atab2.getTableHeader().setFont(new Font("FMBindumathi", Font.BOLD, 18));
             setcolfront();  
            String att="1";
             Connection conn=MysqlConnect.getDbCon();
              Date date = new Date();
            String date1= new SimpleDateFormat("yyyy-MM-dd").format(date);
                            
             String query2="select SalaryNo,Grade,Duty,Availability from DCAttendance where Attendance='"+att+"' and A_Date LIKE '%"+date1+"%'" ;
                    Statement stmt2= conn.createStatement();
                    ResultSet rs2=stmt2.executeQuery(query2);
                    Atab2.setModel(DbUtils.resultSetToTableModel(rs2)); 
                    Atab2.getColumn("SalaryNo").setHeaderValue("fõ;k wxlh  ");
Atab2.getColumn("Grade").setHeaderValue("fY%aKsh ");
Atab2.getColumn("Duty").setHeaderValue("ld¾hh wxlh ");
Atab2.getColumn("Availability").setHeaderValue("ld¾hfha kshq;= ");
Atab2.repaint();
        }catch(Exception e){
            
        }
 }
 
     public void setcolfront() {
        DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
            Font font = new Font("Calibri", Font.BOLD, 14);

            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus,
                    int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus,
                        row, column);
                setFont(font);
                return this;
            }

        };
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Atab1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Atab2 = new javax.swing.JTable();
        gfhfgh2 = new javax.swing.JLabel();
        gfhfgh3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1149, 710));
        setMinimumSize(new java.awt.Dimension(1149, 710));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1149, 710));

        Atab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Atab1.setOpaque(false);
        jScrollPane1.setViewportView(Atab1);

        Atab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Atab2.setOpaque(false);
        jScrollPane2.setViewportView(Atab2);

        gfhfgh2.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        gfhfgh2.setText("wo osk meñK we;s ld¾hd, fiajlhska ");

        gfhfgh3.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        gfhfgh3.setText("wo osk meñK we;s ld¾hd, fkdjk fiajlhska ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(gfhfgh2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gfhfgh3)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gfhfgh2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gfhfgh3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Atab1;
    private javax.swing.JTable Atab2;
    private javax.swing.JLabel gfhfgh2;
    private javax.swing.JLabel gfhfgh3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
