/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SLTB_chamika.employee;

import SLTB_chamika.Class.Employee;
import com.ConnectionMysql.MysqlConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chamika Prabath
 */
public class Webcam extends javax.swing.JPanel {
private static Webcam wc=null;
    /**
    /**
     * Creates new form NewJPanel
     */
    public Webcam() {
        initComponents();
        
    }
public static Webcam getobj(){
       if(wc==null){
            wc=new Webcam();
       }
       return wc;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dailyReport = new javax.swing.JButton();
        monthlyReport = new javax.swing.JButton();
        monLabel = new javax.swing.JLabel();
        rMonth = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(220, 280));
        setMinimumSize(new java.awt.Dimension(220, 280));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(220, 280));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/qrpic.png"))); // NOI18N
        jButton1.setText("Read QR");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dailyReport.setBackground(new java.awt.Color(0, 153, 153));
        dailyReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dailyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/request-report.png"))); // NOI18N
        dailyReport.setText("Daily Report");
        dailyReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dailyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyReportActionPerformed(evt);
            }
        });

        monthlyReport.setBackground(new java.awt.Color(0, 153, 153));
        monthlyReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monthlyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/request-report.png"))); // NOI18N
        monthlyReport.setText("Monthly Report");
        monthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyReportActionPerformed(evt);
            }
        });

        monLabel.setFont(new java.awt.Font("FMBindumathi", 1, 18)); // NOI18N
        monLabel.setForeground(new java.awt.Color(204, 204, 204));
        monLabel.setText("udih ");

        rMonth.setFont(new java.awt.Font("FMBindumathi", 1, 14)); // NOI18N
        rMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ckjdß", "fmnrjdß", "ud¾;=", "wm%sfh,a", "uehs", "cQks", "cQ,s", "wf.daia;=", "iema;eïn¾", "Tlaf;dan¾", "fkdfjïn¾", "foieïn¾" }));
        rMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dailyReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(monthlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(dailyReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthlyReport)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        final Thread thread = new Thread(new Runnable() {
                                           
					@Override
					public void run() {
                                            for(;;){
						try (QrCapture qr = new QrCapture()) {
                                                    Employee e1=new Employee();
							Connection conn=MysqlConnect.getDbCon();
                                                            String salno=qr.getResult();
                                                           String query4="select count(SalaryNo) from Employee where SalaryNo='"+salno+"'";
                                                            Statement stmt4= conn.createStatement();
                                                            ResultSet r4=stmt4.executeQuery(query4);
                                                          while(r4.next()){
				       
                                                            int count=r4.getInt("count(SalaryNo)");
                                                        
                                                            if(count==1){
                                                             String query0="select E_Grade from Employee where SalaryNo='"+salno+"'";
                                                            Statement stmt0= conn.createStatement();
                                                            ResultSet r0=stmt0.executeQuery(query0);
                                                          while(r0.next()){
				       
                                                            String grad=r0.getString("E_Grade");
                                                            if(("Conductor".equals(grad))||("Driver".equals(grad))){
                                                            
                                                            String du=e1.SearchDutyNo(salno);
                                                            String Atten="1";
                                                            String Avail="1";
                                                            String query="select Count(A_ID),A_Date from DCAttendance where SalaryNo='"+salno+"' and OnTime=OffTime and Availability='"+Avail+"'";
                                                            Statement stmt= conn.createStatement();
                                                            ResultSet r=stmt.executeQuery(query);
                                                            
                                                          while(r.next()){
				       
                                                            int i=r.getInt("Count(A_ID)");
                                                            String da=r.getString("A_Date");
                                                            if(i==0){
                                                            
                                                            String query1="select E_Grade from Employee where SalaryNo='"+salno+"'";
                                                            Statement stmt1= conn.createStatement();
                                                            ResultSet r1=stmt1.executeQuery(query1);
                                                          while(r1.next()){
				       
                                                            String gra=r1.getString("E_Grade");
                                                            
                                                

                                                String query2="insert into DCAttendance(SalaryNo,Grade,Duty,Attendance,Availability) values ('"+salno+"','"+gra+"','"+du+"','"+Atten+"','"+Avail+"')";
                                                Statement stmt2= conn.createStatement();
                                                stmt2.executeUpdate(query2);
                                                System.out.println(salno);
        
                                                          } } else{
                                                                Avail="0";
                                                                String Av="1";
                                                                String query3=  "UPDATE DCAttendance SET Availability='"+Avail+"' WHERE SalaryNo='"+salno+"' and OnTime=OffTime and Availability='"+Av+"'";
                                                                Statement stmt3= conn.createStatement();
                                                                stmt3.executeUpdate(query3);
                                                            } } }else{
                                                            
                                                                                String Atten="1";
                                                                                String Avail="1";
                                                                                String query="select Count(A_ID),A_Date from OfficerAttendance where SalaryNo='"+salno+"' and OnTime=OffTime and Availability='"+Avail+"'";
                                                                                Statement stmt= conn.createStatement();
                                                                                ResultSet r=stmt.executeQuery(query);

                                                                              while(r.next()){

                                                                                int i=r.getInt("Count(A_ID)");
                                                                                String da=r.getString("A_Date");
                                                                                if(i==0){

                                                                                String query1="select E_Grade from Employee where SalaryNo='"+salno+"'";
                                                                                Statement stmt1= conn.createStatement();
                                                                                ResultSet r1=stmt1.executeQuery(query1);
                                                                              while(r1.next()){

                                                                                String gra=r1.getString("E_Grade");



                                                                                String query2="insert into OfficerAttendance(SalaryNo,Grade,Attendance,Availability) values ('"+salno+"','"+gra+"','"+Atten+"','"+Avail+"')";
                                                                                Statement stmt2= conn.createStatement();
                                                                                stmt2.executeUpdate(query2);
                                                                                System.out.println(salno);

                                                                              } } else{
                                                                                    Avail="0";
                                                                                   String Av="1";
                                                                                    String query3=  "UPDATE OfficerAttendance SET Availability='"+Avail+"' WHERE SalaryNo='"+salno+"' and OnTime=OffTime and Availability='"+Av+"'";
                                                                                    Statement stmt3= conn.createStatement();
                                                                                    stmt3.executeUpdate(query3);
                                                                                } }
                                                            }}}else{
                                                                showMessage("Employee ID is not Valid, Please Try Again ");
                                                                System.out.println("Invalid ID");
                                                            }}
                                                         
						} catch (InterruptedException ex) {
							ex.printStackTrace();
						} catch (SQLException ex) {
                                                Logger.getLogger(Webcam.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                        }};
                                
				});
				thread.setDaemon(true);
				thread.start();
                                setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dailyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyReportActionPerformed
        // TODO add your handling code here:
        
         Employee e1=new Employee();
        ManageAttendance manageA=ManageAttendance.getobj();
        ManageAttendanceUp manageAup=ManageAttendanceUp.getobj();
      
        if(dailyReport.getText().equalsIgnoreCase("Daily Report")){
            dailyReport.setBackground(new java.awt.Color(255, 51, 51));
            dailyReport.setText("Cancel Report");
            
            manageAup.setVisible(false);
            manageA.setVisible(false);
            monthlyReport.setVisible(false);
            monLabel.setVisible(false);
            rMonth.setVisible(false);
            e1.report("src\\SLTB_chamika\\report\\DailyAttendance.jasper");
           
        }
        else if(dailyReport.getText().equalsIgnoreCase("Cancel Report")){
            dailyReport.setBackground(new java.awt.Color(102, 153, 255));
            dailyReport.setText("Daily Report");
            manageAup.setVisible(true);
            e1.viewer.setVisible(false);
            manageA.setVisible(true);
            monthlyReport.setVisible(true);
            monLabel.setVisible(true);
            rMonth.setVisible(true);
        }
    }//GEN-LAST:event_dailyReportActionPerformed

    private void monthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyReportActionPerformed
        // TODO add your handling code here:
        Employee e1=new Employee();
        ManageAttendance manageA=ManageAttendance.getobj();
        ManageAttendanceUp manageAup=ManageAttendanceUp.getobj();
        String rPath;
        String month = null;
        String saln=manageAup.search.getText();
        String mon= (String) rMonth.getSelectedItem();
               if(mon=="ckjdß"){
                   month="01";
               }else if(mon=="fmnrjdß"){
                   month="02";
               }else if(mon=="ud¾;="){
                   month="03";
               }else if(mon=="wm%sfh,a"){
                   month="04";
               }else if(mon=="uehs"){
                   month="05";
               }else if(mon=="cQks"){
                   month="06";
               }else if(mon=="cQ,s"){
                   month="07";
               }else if(mon=="wf.daia;="){
                   month="08";
               }else if(mon=="iema;eïn¾"){
                   month="09";
               }else if(mon=="Tlaf;dan¾"){
                   month="10";
               }else if(mon=="fkdfjïn¾"){
                   month="11";
               }else if(mon==" foieïn¾"){
                   month="12";
               }
                 
               Date date = new Date();
               String date1= new SimpleDateFormat("yyyy-MM-dd").format(date);
               
               String[] DateParts = date1.split("-");
               
                 String year = DateParts[0];
                 String dash="-";
                 String rym=year+dash+month;
                 System.out.println(rym);   
                
               rPath="src\\SLTB_chamika\\report\\MonthlyAttendance.jasper";
                     
                HashMap par = new HashMap();
                            
                            par.put("salNo", saln);
                            par.put("reYearMonth", rym);

                            if(monthlyReport.getText().equalsIgnoreCase("Monthly Report")){
                                monthlyReport.setBackground(new java.awt.Color(255, 51, 51));
                                monthlyReport.setText("Cancel Report");
                                
                                manageAup.setVisible(false);
                                manageA.setVisible(false);
                                dailyReport.setVisible(false);
                                e1.ParameterizedReport(rPath,par);
                                

                            }
                            else if(monthlyReport.getText().equalsIgnoreCase("Cancel Report")){
                                monthlyReport.setBackground(new java.awt.Color(102, 153, 255));
                                monthlyReport.setText("Monthly Report");

                                e1.viewer.setVisible(false);
                                manageAup.setVisible(true);
                                manageA.setVisible(true);
                                dailyReport.setVisible(true);
                             }
        
    }//GEN-LAST:event_monthlyReportActionPerformed

    private void rMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rMonthActionPerformed


    private void showMessage(String text) {
		JOptionPane.showMessageDialog(null, text);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dailyReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel monLabel;
    private javax.swing.JButton monthlyReport;
    private javax.swing.JComboBox<String> rMonth;
    // End of variables declaration//GEN-END:variables
}
